### ISSUE TITLE
基于0.1.19已经写好koolshare软件中心384/386兼容的版本，怎么提交给你

### ISSUE THREAD

**Issue by flyhigherpi** [messense/aliyundrive-webdav#10]
RT
丢谷歌云盘了
https://drive.google.com/file/d/1iyJ5Z_bUWWbeaXJ0rYyGoIZq6Ckclrky/view?usp=sharing
![image](https://user-images.githubusercontent.com/67776691/131889385-516ec137-f428-4774-89f2-e69ea889cd8e.png)
收工

**Comment by messense** [comment]
Thanks，我看看合并一下。

**Comment by messense** [comment]
@flyhigherpi 可以简单解释一下相比 380 版本修改了什么吗？

**Comment by flyhigherpi** [comment]
> @flyhigherpi 可以简单解释一下相比 380 版本修改了什么吗？

根据384/386的软件中心的API做了调整，这样前后端可以交互了。
页面加了个webdev进程检测。
启动加了弹窗日志查看，目前没单独做日志查看页。

**Comment by messense** [comment]
Merged in https://github.com/messense/aliyundrive-webdav/commit/6afad7f146f7c865bfd38969e8070a608f4abd07#diff-db6cd1edca35de551c57fd102a92f05f01e85fb4c953378d47e3306a1805e4e5R15

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/releases/tag/v0.1.19.post1

![image](https://user-images.githubusercontent.com/1556054/132021144-b57c87ed-790b-45c8-adbc-65f13e0d2c07.png)
