### ISSUE TITLE
0.5.1自动停止未运行？

### ISSUE THREAD

**Issue by cicai1631** [messense/aliyundrive-webdav#107]
Xiaomi Mi Router CR-660x
固件版本：ImmortalWrt 18.06-SNAPSHOT r10213-8c7d866ba / LuCI openwrt-18.06-k5.4 branch (git-21.170.50917-05a4f95)
内核：5.4.124
目前阿里云dav版本是0.5.1 自动停止运行？

**Comment by messense** [comment]
请提供日志。

**Comment by QingHui653** [comment]
刷新token 后,能否将token回填至 输入框?
现在重启或者升级后 需要重新填写token @messense

**Comment by messense** [comment]
@QingHui653 设置 `-w` 参数指定文件夹会将 token 写进文件中，下次启动优先使用 `-r` 如果失效会再次尝试文件中的 token.

**Comment by messense** [comment]
Closing as inactive.
