### ISSUE TITLE
玩客云的S805下哪个版本？

### ISSUE THREAD

**Issue by trunksjiang78** [messense/aliyundrive-webdav#108]
cpu 采用的是晶晨的 s805，这是一款电视盒子上普遍采用的 cpu，采用的是 ARM Cortex-A5 四核架构，单核主频标称 1.5GHz，GPU 是四核 ARM Mali450，加入了对于 1080P H.265 视频的硬件支持，内存采用的是海力士，512*2 共 1GDDR3 内存。闪存是三星的 8g。网口芯片采用的是螃蟹的 rtl6211f 千兆网口

上面是配置，谢谢！

**Comment by messense** [comment]
什么系统？OpenWrt 还是要 docker 跑？

**Comment by trunksjiang78** [comment]
是docker下跑的openwrt

**Comment by messense** [comment]
贴一下 `cat /proc/cpuinto` 和 `opkg print-architecture` 命令的结果。

**Comment by trunksjiang78** [comment]
root@OpenWrt:~# cat /proc/cpuinto
cat: can't open '/proc/cpuinto': No such file or directory
root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch arm_cortex-a5_vfpv4 10

**Comment by messense** [comment]
`cat /proc/cpuinfo`

**Comment by messense** [comment]
[aliyundrive-webdav-openwrt-sama5.zip](https://github.com/messense/aliyundrive-webdav/files/7465525/aliyundrive-webdav-openwrt-sama5.zip)

试下这个行不行？解压后里面有个 ipk 文件。

**Comment by trunksjiang78** [comment]
可以了，非常感谢！！
