### ISSUE TITLE
请问后续版本可否支持多帐号？

### ISSUE THREAD

**Issue by jmheqiao** [messense/aliyundrive-webdav#11]
大神好，部署在路由器上，这是最好的选择。非常好的软件，我已安装到K3的openwrt上，共享给电视播放每集12GB的4K版《世部世界》，结果不卡顿很畅顺。但在我的芝杜X9S盒子的openwrt安装不上，不知有没大神可编译一个适合的版本？
另外我想问下，续版本可否支持多帐号？

**Comment by messense** [comment]
芝杜X9S盒子是什么 CPU 架构？可以贴一下 cat /proc/cpuinfo 输出

多账号暂时没有计划，目前有需要可以命令行启动多个不同 refresh token 的进程。

**Comment by jmheqiao** [comment]
root@OpenWrt:~# cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
BogoMIPS        : 54.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

**Comment by jmheqiao** [comment]
root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch aarch64_cortex-a53 10

**Comment by jmheqiao** [comment]
多谢大神关照！

**Comment by messense** [comment]
二进制应该是兼容的，可以修改 `/etc/opkg.conf` 增加一行 `arch aarch64_generic 100` 然后确认一下 `opkg print-architecture` 输出中包含 `aarch64_generic` 再尝试安装 ipk 文件。

**Comment by jmheqiao** [comment]
按指示做好，还是有问题

root@OpenWrt:/tmp# opkg install aliyundrive-webdav_0.1.19-0_arm_cortex-a9.ipk
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Package aliyundrive-webdav (0.1.19-0) installed in root is up to date.
root@OpenWrt:/tmp# opkg install luci-app-aliyundrive-webdav_0.1.19-0_all.ipk
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Package luci-app-aliyundrive-webdav (0.1.19-0) installed in root is up to date.
root@OpenWrt:/tmp#

可能我的这个芝杜盒子本身的问题吧！

**Comment by messense** [comment]
上面这个日志看起来至少 aliyundrive-webdav 的 ipk 都是安装成功了的。`Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.` 这个报错不一定有实际影响，后台配置下看看能不能跑起来吧。

**Comment by jmheqiao** [comment]
“阿里云盘webdav”没有出来，查过软件包里也没有安装。

**Comment by messense** [comment]
好吧，不行试试 `opkg install --force-overwrite xxx.ipk`

**Comment by jmheqiao** [comment]
成功了！要用 opkg install ****.ipk --force-downgrade 这个指令，非常感谢大神的悉心指导，让我这个小白喜悦万分！

root@OpenWrt:/tmp# opkg install luci-app-aliyundrive-webdav_0.1.19-0_all.ipk --force-downgrade
Package luci-app-aliyundrive-webdav (0.1.19-0) installed in root is up to date.
root@OpenWrt:/tmp# opkg install aliyundrive-webdav_0.1.19-0_aarch64_generic.ipk --force-downgrade
Installing aliyundrive-webdav (0.1.19-0) to root...
Configuring aliyundrive-webdav.

重启后正常运行。

**Comment by messense** [comment]
Great!
