### ISSUE TITLE
windows添加本地位置之后无法打开文件

### ISSUE THREAD

**Issue by onlyJinx** [messense/aliyundrive-webdav#117]
我在本地搭建好之后，在文件管理器里添加本地位置，指向127.0.0.1:8080，添加后图片jpg和png格式可以打开，文本txt格式也可以，但是打不开视频(mp4&mkv)文件，请问是啥问题，本身就不支持的吗

![image](https://user-images.githubusercontent.com/21324835/140504538-72fc676c-e006-470f-93b3-0d2231b4f707.png)

**Comment by messense** [comment]
换个播放器试试？

**Comment by onlyJinx** [comment]
试了一下，win10自带、Potplayer、VLC、迅雷影音都不行。

应该不是播放器的问题，我试着用Potplayer自带的webdav打开(截图)，是可以打开同一部电影的。

RaiDrive没玩明白，不知道为啥一直提示没权限。尴尬

![image](https://user-images.githubusercontent.com/21324835/140527414-5d74060a-f56b-40ef-8472-eea4c06e6c58.png)

![image](https://user-images.githubusercontent.com/21324835/140527562-93685106-a4d2-49a8-bd48-6a6fc3e39b2a.png)

![image](https://user-images.githubusercontent.com/21324835/140527979-aa557d06-8000-428e-9408-b89089dec3da.png)

**Comment by messense** [comment]
可能就是 Windows 资源管理器挂载的问题，没啥办法。

**Comment by underlaw** [comment]
我也是一样

**Comment by onlyJinx** [comment]
> 我也是一样

按照开发者说的使用 RaiDrive 可解决

**Comment by qq57240** [comment]
想想办法对接微软协议吧

**Comment by messense** [comment]
<img width="1030" alt="CleanShot 2021-11-30 at 22 26 40@2x" src="https://user-images.githubusercontent.com/1556054/144065403-a5de821b-cb40-4740-9042-7232d8b3d697.png">

有可能是这个原因，文件 > 50MB 默认不允许下载。

解决方案：https://support.microsoft.com/en-us/topic/folder-copy-error-message-when-downloading-a-file-that-is-larger-than-50000000-bytes-from-a-web-folder-815e2949-0f56-ec25-db7d-b6d860a31f77

**Comment by onlyJinx** [comment]
@messense 按照你的方法后可以解决问题，不过微软似乎对这个FileSizeLimitInBytes值有限制。
还有一个就是播放视频时打开会消耗大量时间(和文件大小成正比)，所以我想问直接用管理器时，它的逻辑是等整个文件下载完之后才让视频播放器开始播放？
而RaiDrive类似于“边下边播”
![11](https://user-images.githubusercontent.com/21324835/144076139-8b3f9e1c-7d60-4c64-b8f1-6756986155fc.png)

![22](https://user-images.githubusercontent.com/21324835/144076064-1ee8da40-9775-4e68-a9d6-75b4a9ac3a15.png)

**Comment by messense** [comment]
> 还有一个就是播放视频时打开会消耗大量时间(和文件大小成正比)，所以我想问直接用管理器时，它的逻辑是等整个文件下载完之后才让视频播放器开始播放？
> 而RaiDrive类似于“边下边播”

很有可能，所以不建议使用 Windows 自带的映射网络驱动器功能，建议使用 RaiDrive.

**Comment by qq57240** [comment]
> <img alt="CleanShot 2021-11-30 at 22 26 40@2x" width="1030" src="https://user-images.githubusercontent.com/1556054/144065403-a5de821b-cb40-4740-9042-7232d8b3d697.png">
> 
> 有可能是这个原因，文件 > 50MB 默认不允许下载。
> 
> 解决方案：https://support.microsoft.com/en-us/topic/folder-copy-error-message-when-downloading-a-file-that-is-larger-than-50000000-bytes-from-a-web-folder-815e2949-0f56-ec25-db7d-b6d860a31f77

好家伙，m司限制成50m，那还够干嘛。。。

**Comment by mintisan** [comment]
我也碰到了，所以 windows 自带的就是一个残次品，，，

**Comment by mintisan** [comment]
可以参考 https://www.topsite.jp/docs/windows-webdav-limit 这个链接修改， 现在打开不会报错，直接资源管理器直接卡死，，，还是残次品，，，
