### ISSUE TITLE
Nas的网盘同歩完的文件网页版和手机app都看不到。

### ISSUE THREAD

**Issue by Babyvox550** [messense/aliyundrive-webdav#118]
Nas的网盘同歩完的文件网页版和手机app都看不到。

**Comment by Babyvox550** [comment]
![Screenshot_20211105_221606](https://user-images.githubusercontent.com/13328183/140525014-471a6047-4cf1-42a3-9806-c27b1a139bdd.jpg)
![Screenshot_20211105_221356](https://user-images.githubusercontent.com/13328183/140525021-16ecc2b6-2d26-4505-886d-9f6dd2dbe592.jpg)

**Comment by messense** [comment]
看看有没有错误日志。

**Comment by Babyvox550** [comment]
![Uploading Screenshot_20211106_131223.jpg…]()

**Comment by Babyvox550** [comment]
![Screenshot_20211106_131223](https://user-images.githubusercontent.com/13328183/140598847-c2ceaec0-d025-43f1-8cb2-708719f55f84.jpg)

**Comment by messense** [comment]
看起来是一些网络问题，超时、DNS 解析不了之类的。

**Comment by Babyvox550** [comment]
用这里的能用。。。。https://github.com/zxbu/webdav-aliyundriver

**Comment by messense** [comment]
嗯，那就用那个版本。
