### ISSUE TITLE
可以监听ipv6地址吗？

### ISSUE THREAD

**Issue by liujixu1984** [messense/aliyundrive-webdav#12]
我是用的openwrt,安装好以后发现ipv6的地址访问不了！想请问一下可以监听v4和v6不，还有能否多开？我有两个网盘账号都想挂上来！

**Comment by messense** [comment]
可以试试配置监听主机为 `::0`；可以多开，多开需要手动运行指定不同的端口，参考 https://github.com/messense/aliyundrive-webdav#%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%94%A8%E6%B3%95
