### ISSUE TITLE
命令行运行提示Illegal instruction

### ISSUE THREAD

**Issue by liujixu1984** [messense/aliyundrive-webdav#13]
aliyundrive-webdav --auto-index --cache-size 1000 --host 0 --port 8085 --read-buffer-size 10485760 --refresh-token XXXX
aliyundrive-webdav -I --host ::0 --port 5003 -S 10485760 --cache-size 1000 -r XXXXX -W admin -U admin
按照官方使用说明，以上两条命令行在ssh 运行都出现以下提示：

Sep 04 10:53:00.173  INFO aliyundrive_webdav::drive: refresh token succeed refresh_token=fd2a5db1df774acXXXXXXXX0328c1bd1 nick_name=摸摸么
Sep 04 10:53:00.173  INFO aliyundrive_webdav::drive: found default drive drive_id=1543251
Sep 04 10:53:00.174  INFO aliyundrive_webdav: listening on 0.0.0.0:8085
Illegal instruction

**Comment by liujixu1984** [comment]
后面测试网页版发现也没法正常使用，都显示aliyundrive-webdav 0.1.19 未运行

**Comment by messense** [comment]
什么系统？cpu 架构？贴一下 cat /proc/cpuinfo 的输出吧

**Comment by liujixu1984** [comment]
是pve虚拟机安装的openwrt x86-64 一下是cpuinfo信息

BusyBox v1.30.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 19.07-SNAPSHOT, r11386-711e7acd6d
 -----------------------------------------------------
root@OpenWrt:~# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2127.998
cache size      : 16384 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                  pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology                                                                                                  cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                  swapgs itlb_multihit
bogomips        : 4255.99
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2127.998
cache size      : 16384 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                  pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology                                                                                                  cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                  swapgs itlb_multihit
bogomips        : 4255.99
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2127.998
cache size      : 16384 KB
physical id     : 1
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                  pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology                                                                                                  cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                  swapgs itlb_multihit
bogomips        : 4255.99
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2127.998
cache size      : 16384 KB
physical id     : 1
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                  pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology                                                                                                  cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                  swapgs itlb_multihit
bogomips        : 4255.99
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:

**Comment by messense** [comment]
应该是 CI 编译的版本包含了 AVX 指令集，你的虚拟机不支持。
