### ISSUE TITLE
无法安装 luci-app-aliyundrive-webdav和luci-i18n-aliyundrive-webdav-zh-cn_0.5.4-1_all

### ISSUE THREAD

**Issue by sherlockHlb** [messense/aliyundrive-webdav#135]
### 问题描述

```bash
Installing luci-app-aliyundrive-webdav (0.5.4) to root...
Configuring luci-app-aliyundrive-webdav.
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
Installing luci-i18n-aliyundrive-webdav-zh-cn (0.5.4-1) to root...
Configuring luci-i18n-aliyundrive-webdav-zh-cn.
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
```

### 重现步骤

路由为 Xiaomi Redmi Router AC2100 (CpuMark : 4537.891393 Scores)

安装版本0.5.4

### 版本

0.5.4

### 运行平台

Xiaomi Redmi Router AC2100

**Comment by messense** [comment]
cc @Beginner-Go Any idea?

**Comment by messense** [comment]
我好像也遇到过，安装/升级的时候有这个报错信息，但对实际使用没有影响。

**Comment by sherlockHlb** [comment]
当我尝试重新安装,
提示:/tmp/tmp$ opkg install luci-i18n-aliyundrive-webdav-zh-cn_0.5.4-1_all.ipk
Package luci-i18n-aliyundrive-webdav-zh-cn (0.5.4-1) installed in root is up to date.
但是在软件包内,并没有发现 luci-app-aliyundrive-webdav_0.5.4_all以及 luci-i18n-aliyundrive-webdav-zh-cn_0.5.4-1_all

**Comment by messense** [comment]
先卸载再安装呢？

**Comment by sherlockHlb** [comment]
![QQ截图20211108102208](https://user-images.githubusercontent.com/30238046/140674492-4c3891c9-4592-4e1e-b670-824efc1b4660.png)
没有显示版本,也无法运行.

**Comment by sherlockHlb** [comment]
卸载aliyundrive-webdav后重新安装
aliyundrive-webdav可以安装
剩下两个依然如此提示.

**Comment by sherlockHlb** [comment]
这次可以看到<html>
<body>


luci-app-aliyundrive-webdav
--


<br class="Apple-interchange-newline">
</body>
</html>和<html>
<body>


luci-i18n-aliyundrive-webdav-zh-cn
--


<br class="Apple-interchange-newline">
</body>
</html>了.
但是依然无法运行.

**Comment by messense** [comment]
感觉少装了主 aliyundrive-webdav_XXXX.ipk 那个，命令行执行 `aliyundrive-webdav --help` 看看是不是报错命令不存在。

**Comment by sherlockHlb** [comment]
/tmp/tmp$ opkg install aliyundrive-webdav_0.5.4_mipsel_24kc.ipk
Installing aliyundrive-webdav (0.5.4) to root...
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/aliyundrive-webdav is different from the conffile in the new package. The new conffile will be placed at /etc/config/aliyundrive-webdav-opkg.
Configuring aliyundrive-webdav.
/tmp/tmp$ opkg install luci-app-aliyundrive-webdav_0.5.4_all.ipk
Installing luci-app-aliyundrive-webdav (0.5.4) to root...
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
Configuring luci-app-aliyundrive-webdav.
/tmp/tmp$ opkg install luci-i18n-aliyundrive-webdav-zh-cn_0.5.4-1_all.ipk
Installing luci-i18n-aliyundrive-webdav-zh-cn (0.5.4-1) to root...
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
Configuring luci-i18n-aliyundrive-webdav-zh-cn.

**Comment by sherlockHlb** [comment]
命令行执行 aliyundrive-webdav --help

失败并返回错误127
无内容

**Comment by messense** [comment]
应该被安装在了 `/usr/bin/aliyundrive-webdav` 看看完整路径是否可以执行，`echo $PATH` 看看 PATH 配置是否有问题。

**Comment by sherlockHlb** [comment]
/usr/bin/aliyundrive-webdav有文件
但是执行/usr/bin$ aliyundrive-webdav --help
依然是返回错误127

**Comment by sherlockHlb** [comment]
![image](https://user-images.githubusercontent.com/30238046/140675806-1c3e8ae3-6ca3-44c0-be63-d42902423a91.png)

**Comment by sherlockHlb** [comment]
![QQ截图20211108102208](https://user-images.githubusercontent.com/30238046/140675868-bc440b08-a213-49e3-8636-85d054dc8f89.png)

**Comment by messense** [comment]
`file /usr/bin/aliyundrive-webdav` 看下，没有 file 命令的话用 opkg install file 安装。

**Comment by sherlockHlb** [comment]
能够看到,但是提示
-ash: file: not found
![image](https://user-images.githubusercontent.com/30238046/140678263-db4c8689-d61d-41b7-a2d4-bc83789a97b0.png)
运行 opkg install /tmp/tmp/aliyundrive-webdav_0.5.4_mipsel_24kc.ipk
返回Package aliyundrive-webdav (0.5.4) installed in root is up to date.

**Comment by messense** [comment]
上面已经说了

> 没有 file 命令的话用 opkg install file 安装

**Comment by sherlockHlb** [comment]
opkg install file 里的file指的是路径还是
这就是一条命令
![image](https://user-images.githubusercontent.com/30238046/140679107-2614f83a-7de0-495b-9b37-556b2c2b8994.png)
是这样吗?

**Comment by messense** [comment]
1. `file /usr/bin/aliyundrive-webdav`
2. `ls -lrth /usr/bin/aliyundrive-webdav`

分别执行看下输出。

**Comment by sherlockHlb** [comment]
opkg install file后出现新的错误
/tmp/tmp$ file /usr/bin/aliyundrive-webdav
Error relocating /usr/lib/libmagic.so.1: __utimes_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __mktime64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __gmtime64_r: symbol not found
Error relocating /usr/lib/libmagic.so.1: __localtime64_r: symbol not found
Error relocating /usr/lib/libmagic.so.1: __stat_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __fstat_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __ctime64_r: symbol not found
Error relocating /usr/lib/libmagic.so.1: __select_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __lstat_time64: symbol not found
Error relocating /usr/lib/liblzma.so.5: __clock_gettime64: symbol not found
Error relocating /usr/lib/liblzma.so.5: __pthread_cond_timedwait_time64: symbol not found

**Comment by messense** [comment]
系统有点问题吧。

`/usr/bin/aliyundrive-webdav --help` 看下。

**Comment by sherlockHlb** [comment]
仍然错误127

**Comment by messense** [comment]
这个报错 127 没有道理，感觉你的 OpenWrt 系统有问题，建议重装/换个版本。

**Comment by sherlockHlb** [comment]
好的,那我尝试一下

**Comment by sherlockHlb** [comment]
那么顺便问一下,如果是 mipsel_1004kc_dsp 怎么安装呢.
因为不会自己编译

**Comment by messense** [comment]
> 那么顺便问一下,如果是 mipsel_1004kc_dsp 怎么安装呢. 因为不会自己编译

这个是什么路由器？

**Comment by sherlockHlb** [comment]
> > 那再问一下，如果是mipsel_1004kc_dsp怎么安装呢。因为不会自己编译
> 
> 这是什么路由器？

newifi 3
刷的openwrt

**Comment by sherlockHlb** [comment]
换了个版本的openwrt依然是这个问题

/tmp/tmp$ file /usr/bin/aliyundrive-webdav
Error relocating /usr/lib/libmagic.so.1: __utimes_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __mktime64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __gmtime64_r: symbol not found
Error relocating /usr/lib/libmagic.so.1: __localtime64_r: symbol not found
Error relocating /usr/lib/libmagic.so.1: __stat_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __fstat_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __ctime64_r: symbol not found
Error relocating /usr/lib/libmagic.so.1: __select_time64: symbol not found
Error relocating /usr/lib/libmagic.so.1: __lstat_time64: symbol not found
Error relocating /usr/lib/liblzma.so.5: __clock_gettime64: symbol not found
Error relocating /usr/lib/liblzma.so.5: __pthread_cond_timedwait_time64: symbol not found
/tmp/tmp$ ls -lrth /usr/bin/aliyundrive-webdav
-rwxr-xr-x    1 root     root        3.2M Nov  6 18:56 /usr/bin/aliyundrive-webdav

**Comment by sherlockHlb** [comment]
我尝试使用这个插件.
可以正常挂载
https://www.right.com.cn/forum/thread-5841157-1-1.html

**Comment by messense** [comment]
> > > 那再问一下，如果是mipsel_1004kc_dsp怎么安装呢。因为不会自己编译
> > 
> > 
> > 这是什么路由器？
> 
> newifi 3 刷的openwrt

OpenWrt wiki 里面没有这个架构：https://openwrt.org/docs/techref/instructionset/start

**Comment by Beginner-Go** [comment]
二进制有0755权限吗？

**Comment by sherlockHlb** [comment]
> > > > 那再问一下，如果是mipsel_1004kc_dsp安装呢。
> > > 
> > > 
> > > 这是什么伴侣？
> > 
> > 
> > newifi 3刷的openwrt
> 
> OpenWrt wiki里面没有这个目录：https://openwrt.org/docs/techref/instructionset/start

![UN}DB@CV`U8A8@P KL6@(HW](https://user-images.githubusercontent.com/30238046/140700497-112a2258-ed3e-4603-90d7-471760b39397.png)
..............

**Comment by sherlockHlb** [comment]
![UN}DB@CV`U8A8@P KL6@(HW](https://user-images.githubusercontent.com/30238046/140700954-4d5f3019-387c-4be7-966d-a4d2c9b41be7.png)

**Comment by Beginner-Go** [comment]
建议用高内核版本的openwrt试试

**Comment by messense** [comment]
可以尝试执行 `ldd ./aliyundrive-webdav` 看看输出。

**Comment by messense** [comment]
应该是 #136 一样的问题。

**Comment by messense** [comment]
mipsel_24kc 可以试一下 0.5.5 版本：https://github.com/messense/aliyundrive-webdav/releases/tag/v0.5.5

**Comment by messense** [comment]
> > > 那再问一下，如果是mipsel_1004kc_dsp怎么安装呢。因为不会自己编译
> > 
> > 
> > 这是什么路由器？
> 
> newifi 3 刷的openwrt

可以直接把 opkg print-architecture 的输出复制粘贴到 `/etc/opkg.conf` 中并增加一行 `arch mipsel_24kc 100` 保存安装安装 mipsel_24kc 版本，应该是兼容的。
