### ISSUE TITLE
mipsel-unknown-linux-musl 无法运行

### ISSUE THREAD

**Issue by onlyJinx** [messense/aliyundrive-webdav#136]
### 问题描述

运行后没有任何反应，校验过sha256是正确的，重新下载也不行，请问有可能是什么原因？

![image](https://user-images.githubusercontent.com/21324835/140716939-e9a5b57d-6d70-4e1b-a9e8-cdf3534f831d.png)

### 版本

v0.5.4

### 运行平台

路由器 老毛子固件

**Comment by messense** [comment]
没用过老毛子固件，dmesg 看下有没有什么内核报错信息？

**Comment by onlyJinx** [comment]
log如下，请帮忙看看，谢谢

``
BusyBox v1.29.3 (2021-09-24 13:34:05 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

[JDC-1 3.4.3.9-099_21-10-3]# 2021-11-08 17:55:08
[JDC-1 /opt/home/admin]#
[JDC-1 /opt/home/admin]#
[JDC-1 /opt/home/admin]#
[JDC-1 /opt/home/admin]# cd /tmp
[JDC-1 /tmp]# ls
AiDisk_00
AiDisk_opt
aliyundrive-webdav
aliyundrive-webdav-v0.5.4.mipsel-unknown-linux-musl.tar.gz
ap2g5g
ap2g5g.txt
app_ver_n.txt
basedomain.txt
[JDC-1 /tmp]# ./aliyundrive-webdav
[JDC-1 /tmp]# dmesg
0 channel = 36
[   18.640000] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
[   18.647000] device rai0 entered promiscuous mode
[   18.699000] apclii0: ===> apcli_virtual_if_open
[   18.704000] RTMP_COM_IoctlHandle -> CMD_RTPRIV_IOCTL_VIRTUAL_INF_UP
[   18.710000] wifi_sys_open(), wdev idx = 6
[   18.714000]  [RadarStateCheck] RD_NORMAL_MODE
[   18.720000] Caller: 0x99ce1ac0
[   18.723000] phy_mode=49, ch=36, wdev_type=128
[   18.727000] ht_cap->HtCapInfo: ldpc=0,ch_width=1,gf=0,sgi20=1,sgi40=1,tx_stbc=1,rx_stbc=1,amsdu_size=1
[   18.736000] ht_cap->HtCapParm: mdpu_density=0, ampdu_factor=3
[   18.742000] APCLI inf up for apcli_0(func_idx) OmacIdx=1
[   18.748000] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
[   18.761000] ExtEventBeaconLostHandler::FW LOG, Beacon lost (8c:88:2b:00:00:00), Reason 0x10
[   18.769000]   Beacon lost - AP disabled!!!
[   18.782000] load_dev_l1profile()-->
[   18.786000] l1set_profile_path() profile remain /etc/Wireless/RT2860/RT2860AP.dat
[   18.793000] l1set_eeprom_offset() eeprom offset remain 0x0
[   18.799000] l1set_eeprom_size() eeprom size remain 0x200
[   18.804000] l1set_ifname() ifname rename from ra0 to ra
[   18.810000] l1set_ifname() ifname remain ra
[   18.814000] l1set_ifname() ifname remain ra
[   18.818000] l1set_ifname() ifname remain wds
[   18.823000] l1set_ifname() ifname remain apcli
[   18.828000] TX_BCN DESC bb294000 size = 320
[   18.832000] RX[0] DESC bb296000 size = 2048
[   18.837000] RX[1] DESC bb297000 size = 2048
[   18.844000] E2pAccessMode=2
[   18.847000] cfg_mode=7
[   18.850000] cfg_mode=7
[   18.852000] wmode_band_equal(): Band Equal!
[   18.992000] Key1Str is Invalid key length(0) or Type(0)
[   18.998000] Key1Str is Invalid key length(0) or Type(0)
[   19.003000] Key2Str is Invalid key length(0) or Type(0)
[   19.009000] Key2Str is Invalid key length(0) or Type(0)
[   19.014000] Key3Str is Invalid key length(0) or Type(0)
[   19.020000] Key3Str is Invalid key length(0) or Type(0)
[   19.025000] Key4Str is Invalid key length(0) or Type(0)
[   19.031000] Key4Str is Invalid key length(0) or Type(0)
[   19.579000] FW Version:CL173766_R
[   19.583000] FW Build Date:20171110105932
[   19.587000] CmdAddressLenReq:(ret = 0)
[   19.592000] CmdFwStartReq: override = 1, address = 1048576
[   19.597000] CmdStartDLRsp: WiFI FW Download Success
[   19.617000] AsicDMASchedulerInit(): DMA Scheduler Mode=0(LMAC)
[   19.623000] efuse_probe: efuse = 10000002
[   19.627000] RtmpChipOpsEepromHook::e2p_type=2, inf_Type=5[   19.633000] RtmpEepromGetDefault::e2p_dafault=1
[   19.637000] RtmpChipOpsEepromHook: E2P type(2), E2pAccessMode = 2, E2P default = 1
[   19.645000] NVM is FLASH mode, flash_offset = 0x40000
[   19.650000] 1. Phy Mode = 12
[   19.653000] @@@  NICReadEEPROMParameters : pAd->FWLoad=0 [   19.814000] Country Region from e2p = ffff
[   19.818000] tssi_1_target_pwr_g_band = 16
[   19.822000] 2. Phy Mode = 12
[   19.825000] 3. Phy Mode = 12
[   19.828000] NICInitPwrPinCfg(14): Not support for HIF_MT yet!
[   19.834000] NICInitializeAsic(588): Not support rtmp_mac_sys_reset () for HIF_MT yet!
[   19.842000] mt_mac_init()-->
[   19.844000] mt7603_init_mac_cr()-->
[   19.848000] AsicSetMacMaxLen(1907): Set the Max RxPktLen=1024!
[   19.854000] <--mt_mac_init()
[   19.857000]  WTBL Segment 1 info:
[   19.861000]          MemBaseAddr/FID:0x28000/0
[   19.864000]          EntrySize/Cnt:32/128
[   19.868000]  WTBL Segment 2 info:
[   19.871000]          MemBaseAddr/FID:0x40000/0
[   19.875000]          EntrySize/Cnt:64/128
[   19.878000]  WTBL Segment 3 info:
[   19.882000]          MemBaseAddr/FID:0x42000/64
[   19.886000]          EntrySize/Cnt:64/128
[   19.889000]  WTBL Segment 4 info:
[   19.892000]          MemBaseAddr/FID:0x44000/128
[   19.896000]          EntrySize/Cnt:32/128
[   19.900000] AntCfgInit(2689): Not support for HIF_MT yet![   19.905000] RTMPSetPhyMode(): channel out of range, use first ch=0
[   19.912000] MCS Set = ff ff 00 00 01
[   21.775000] scan_ch_restore,central ch=42,bw=2
APStop(), oper(1) bssid(0)=8c:88:2b:00:00:00
[   22.150000] wifi_sys_linkdown(), wdev idx = 0
[   22.155000] ExtEventBeaconLostHandler::FW LOG, Beacon lost (8c:88:2b:00:00:00), Reason 0x10
[   22.163000]   Beacon lost - AP disabled!!!
[   22.168000] bssUpdateBmcMngRate (BSS_INFO_BROADCAST_INFO), CmdBssInfoBmcRate.u2BcTransmit= 0, CmdBssInfoBmcRate.u2McTransmit = 0
[   22.180000] wifi_sys_close(), wdev idx = 0
[   23.184000] mlme can't polling to idle, timeout
[   23.188000] <=== APStop()
[   23.191000] APStartUp(), oper(1) bssid(0)=8c:88:2b:00:00:00
[   23.197000] wifi_sys_open(), wdev idx = 0
[   23.201000] wdev_attr_update(): wdevId0 = 8c:88:2b:00:00:00
[   23.206000]  [RadarStateCheck] RD_NORMAL_MODE
[   23.212000] Caller: 0x99ce1ac0
[   23.215000] phy_mode=49, ch=64, wdev_type=1
[   23.219000] ht_cap->HtCapInfo: ldpc=0,ch_width=1,gf=0,sgi20=1,sgi40=1,tx_stbc=1,rx_stbc=1,amsdu_size=1
[   23.228000] ht_cap->HtCapParm: mdpu_density=5, ampdu_factor=3
[   23.234000] AP inf up for ra_0(func_idx) OmacIdx=0
[   23.239000] AsicRadioOnOffCtrl(): DbdcIdx=0 RadioOn
[   23.244000] ApAutoChannelAtBootUp----------------->
[   23.249000] ApAutoChannelAtBootUp: AutoChannelBootup[0] = 0
[   23.255000] ApAutoChannelAtBootUp<-----------------
[   23.260000]  ap_run_at_boot() : ACS is disable !!
[   23.265000] [PMF]APPMFInit:: apidx=0, MFPC=0, MFPR=0, SHA256=0
[   23.271000] wifi_sys_linkup(), wdev idx = 0
[   23.275000] wtc_acquire_groupkey_wcid: Found a non-occupied wtbl_idx:127 for WDEV_TYPE:1
[   23.275000]  LinkToOmacIdx = 0, LinkToWdevType = 1
[   23.419000] bssUpdateBmcMngRate (BSS_INFO_BROADCAST_INFO), CmdBssInfoBmcRate.u2BcTransmit= 8192, CmdBssInfoBmcRate.u2McTransmit = 8192
[   23.432000] UpdateBeaconHandler, BCN_UPDATE_INIT, OmacIdx = 0
[   23.437000] APStartUpForMbss: BssIndex = 0 channel = 64
[   23.443000] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
[   23.449000] [PMF]APPMFInit:: apidx=0, MFPC=0, MFPR=0, SHA256=0
[   23.455000] APStartUpForMbss: BssIndex = 0 channel = 64
[   23.460000] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
[   23.466000] WifiFwdSet::disabled=0
[   23.469000] Main bssid = 8c:88:2b:00:00:00
[   28.213000] =====================================================
[   28.219000] Channel 1 : Dirty = 1154, False CCA = 0, Busy Time = 14230, Skip Channel = FALSE
[   28.227000] Channel 2 : Dirty = 1148, False CCA = 0, Busy Time = 15772, Skip Channel = FALSE
[   28.236000] Channel 3 : Dirty = 1148, False CCA = 0, Busy Time = 9869, Skip Channel = FALSE
[   28.244000] Channel 4 : Dirty = 1312, False CCA = 0, Busy Time = 12653, Skip Channel = FALSE
[   28.253000] Channel 5 : Dirty = 1168, False CCA = 0, Busy Time = 11936, Skip Channel = FALSE
[   28.261000] Channel 6 : Dirty = 1380, False CCA = 0, Busy Time = 27248, Skip Channel = FALSE
[   28.270000] Channel 7 : Dirty = 1352, False CCA = 0, Busy Time = 28028, Skip Channel = FALSE
[   28.278000] Channel 8 : Dirty = 1402, False CCA = 0, Busy Time = 37284, Skip Channel = FALSE
[   28.287000] Channel 9 : Dirty = 1364, False CCA = 0, Busy Time = 16957, Skip Channel = FALSE
[   28.295000] Channel 10 : Dirty = 1336, False CCA = 0, Busy Time = 11010, Skip Channel = FALSE
[   28.304000] Channel 11 : Dirty = 1712, False CCA = 0, Busy Time = 21460, Skip Channel = FALSE
[   28.312000] Channel 12 : Dirty = 1040, False CCA = 0, Busy Time = 18696, Skip Channel = FALSE
[   28.321000] Channel 13 : Dirty = 970, False CCA = 0, Busy Time = 11177, Skip Channel = FALSE
[   28.329000] =====================================================
[   28.335000] Rule 1 CCA value : Min Dirtiness (Include extension channel) ==> Select Channel 1
[   28.344000] Min Dirty = 2322
[   28.347000] ExChannel = 5 , 0
[   28.350000] BW        = 40
[   28.482000] AsicSetRalinkBurstMode(4325): Not support for HIF_MT yet!
[   28.489000] RTMPSetPiggyBack(943): Not support for HIF_MT yet!
[   28.501000] AsicSetTxPreamble(4312): Not support for HIF_MT yet!
[   28.509000] AsicSetPreTbtt(): bss_idx=0, PreTBTT timeout = 0xa0
[   28.515000] Main bssid = 8c:88:2b:00:00:90
[   28.520000] <==== rt28xx_init, Status=0
[   28.549000] @@@ ed_monitor_exit : ===>
[   28.553000] @@@ ed_monitor_exit : <===
[   28.557000] mt7603_set_ed_cca: TURN OFF EDCCA  mac 0x10618 = 0x8564267c, EDCCA_Status=0
[   28.565000] WiFi Startup Cost (ra0): 9.783s
[   28.570000] device ra0 entered promiscuous mode
[   29.598000] br0: port 3(ra0) entered forwarding state
[   29.603000] br0: port 3(ra0) entered forwarding state
[   29.608000] br0: port 2(rai0) entered forwarding state
[   29.613000] br0: port 2(rai0) entered forwarding state
[   29.618000] br0: port 1(eth2) entered forwarding state
[   29.623000] br0: port 1(eth2) entered forwarding state
[   29.646000] mtk_esw - software IGMP/MLD snooping: 1
[   29.900000] eth3: ===> VirtualIF_open
[   29.987000] Ralink HW NAT v2.52.0 Module Enabled, FoE Size: 16384
[   30.030000] ExtEventBeaconLostHandler::FW LOG, Beacon lost (8c:88:2b:00:00:00), Reason 0x10
[   30.039000]   Beacon lost - AP disabled!!!
[   31.608000] br0: port 3(ra0) entered forwarding state
[   31.616000] br0: port 2(rai0) entered forwarding state
[   31.624000] br0: port 1(eth2) entered forwarding state
[   32.276000] scan_ch_restore,central ch=58,bw=2
APStop(), oper(1) bssid(0)=8c:88:2b:00:00:00
[   32.286000] wifi_sys_linkdown(), wdev idx = 0
[   32.291000] ExtEventBeaconLostHandler::FW LOG, Beacon lost (8c:88:2b:00:00:00), Reason 0x10
[   32.299000]   Beacon lost - AP disabled!!!
[   32.304000] bssUpdateBmcMngRate (BSS_INFO_BROADCAST_INFO), CmdBssInfoBmcRate.u2BcTransmit= 0, CmdBssInfoBmcRate.u2McTransmit = 0
[   32.316000] wifi_sys_close(), wdev idx = 0
[   33.320000] mlme can't polling to idle, timeout
[   33.324000] <=== APStop()
[   33.327000] APStartUp(), oper(1) bssid(0)=8c:88:2b:00:00:00
[   33.333000] wifi_sys_open(), wdev idx = 0
[   33.337000] wdev_attr_update(): wdevId0 = 8c:88:2b:00:00:00
[   33.342000]  [RadarStateCheck] RD_NORMAL_MODE
[   33.348000] Caller: 0x99ce1ac0
[   33.351000] phy_mode=49, ch=64, wdev_type=1
[   33.355000] ht_cap->HtCapInfo: ldpc=0,ch_width=1,gf=0,sgi20=1,sgi40=1,tx_stbc=1,rx_stbc=1,amsdu_size=1
[   33.364000] ht_cap->HtCapParm: mdpu_density=5, ampdu_factor=3
[   33.370000] AP inf up for ra_0(func_idx) OmacIdx=0
[   33.375000] AsicRadioOnOffCtrl(): DbdcIdx=0 RadioOn
[   33.380000] ApAutoChannelAtBootUp----------------->
[   33.385000] ApAutoChannelAtBootUp: AutoChannelBootup[0] = 0
[   33.391000] ApAutoChannelAtBootUp<-----------------
[   33.395000]  ap_run_at_boot() : ACS is disable !!
[   33.401000] [PMF]APPMFInit:: apidx=0, MFPC=0, MFPR=0, SHA256=0
[   33.407000] wifi_sys_linkup(), wdev idx = 0
[   33.411000] wtc_acquire_groupkey_wcid: Found a non-occupied wtbl_idx:127 for WDEV_TYPE:1
[   33.411000]  LinkToOmacIdx = 0, LinkToWdevType = 1
[   33.554000] bssUpdateBmcMngRate (BSS_INFO_BROADCAST_INFO), CmdBssInfoBmcRate.u2BcTransmit= 8192, CmdBssInfoBmcRate.u2McTransmit = 8192
[   33.567000] UpdateBeaconHandler, BCN_UPDATE_INIT, OmacIdx = 0
[   33.574000] APStartUpForMbss: BssIndex = 0 channel = 64
[   33.579000] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
[   33.585000] [PMF]APPMFInit:: apidx=0, MFPC=0, MFPR=0, SHA256=0
[   33.591000] APStartUpForMbss: BssIndex = 0 channel = 64
[   33.596000] MtCmdTxPowerDropCtrl: ucPowerDrop: 100, BandIdx: 0
[   33.603000] WifiFwdSet::disabled=0
[   33.606000] Main bssid = 8c:88:2b:00:00:00
[   34.580000] ApCliValidateRSNIE(): Candidate Security AKMMap=WPA2PSK, PairwiseCipher=AES, GroupCipher=TKIP
[   35.711000] (ApCliLinkUp) ifIndex = 0!!!
[   35.715000] wifi_sys_linkup(), wdev idx = 6
[   35.719000] wtc_acquire_groupkey_wcid: Found a non-occupied wtbl_idx:126 for WDEV_TYPE:128
[   35.719000]  LinkToOmacIdx = 1, LinkToWdevType = 128
[   35.733000] bssUpdateBmcMngRate (BSS_INFO_BROADCAST_INFO), CmdBssInfoBmcRate.u2BcTransmit= 8192, CmdBssInfoBmcRate.u2McTransmit = 8196
[   35.773000] oooWPAParseEapolKeyData : the Group install  (1)
[   64.803000] Load Ralink WDG Timer Module
[   74.576000] EXT4-fs (mmcblk0): mounted filesystem with ordered data mode. Opts: (null)
[ 9549.754000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[16663.648000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[16663.656000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[17231.054000] MIC Different in pairwise msg 2 of 4-way handshake!
[17232.062000] MIC Different in pairwise msg 2 of 4-way handshake!
[17234.128000] MIC Different in pairwise msg 2 of 4-way handshake!
[34002.052000] WpaEAPOLStartAction, cannot find entry:54:0e:58:37:92:0d
[34032.437000] MIC Different in pairwise msg 2 of 4-way handshake!
[34033.448000] MIC Different in pairwise msg 2 of 4-way handshake!
[34034.508000] MIC Different in pairwise msg 2 of 4-way handshake!
[36580.996000] MIC Different in pairwise msg 2 of 4-way handshake!
[36583.039000] MIC Different in pairwise msg 2 of 4-way handshake!
[36584.082000] MIC Different in pairwise msg 2 of 4-way handshake!
[44328.353000] MIC Different in pairwise msg 2 of 4-way handshake!
[44330.402000] MIC Different in pairwise msg 2 of 4-way handshake!
[49226.502000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[49226.509000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[120316.825000] MIC Different in pairwise msg 2 of 4-way handshake!
[120318.930000] MIC Different in pairwise msg 2 of 4-way handshake!
[210864.348000] MIC Different in pairwise msg 2 of 4-way handshake!
[210865.362000] MIC Different in pairwise msg 2 of 4-way handshake!
[210866.419000] MIC Different in pairwise msg 2 of 4-way handshake!
[210867.446000] MIC Different in pairwise msg 2 of 4-way handshake!
[210870.827000] MIC Different in pairwise msg 2 of 4-way handshake!
[210871.820000] MIC Different in pairwise msg 2 of 4-way handshake!
[296156.428000] dev_rx_ctrl_frm(): Cannot found WCID of BAR packet!
[296156.434000] dev_rx_ctrl_frm(): Cannot found WCID of BAR packet!
[303335.236000] MIC Different in pairwise msg 2 of 4-way handshake!
[303336.237000] MIC Different in pairwise msg 2 of 4-way handshake!
[303337.268000] MIC Different in pairwise msg 2 of 4-way handshake!
[303338.403000] MIC Different in pairwise msg 2 of 4-way handshake!
[389787.800000] MIC Different in pairwise msg 2 of 4-way handshake!
[389788.822000] MIC Different in pairwise msg 2 of 4-way handshake!
[403628.859000] MIC Different in pairwise msg 2 of 4-way handshake!
[403629.853000] MIC Different in pairwise msg 2 of 4-way handshake!
[452954.048000] MIC Different in pairwise msg 2 of 4-way handshake!
[452955.111000] MIC Different in pairwise msg 2 of 4-way handshake!
[452956.145000] MIC Different in pairwise msg 2 of 4-way handshake!
[452957.257000] MIC Different in pairwise msg 2 of 4-way handshake!
[543305.721000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[543305.728000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[550293.494000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[550293.502000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[550293.509000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[563592.708000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[563592.715000] BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
[625194.272000] MIC Different in pairwise msg 2 of 4-way handshake!
[625197.351000] MIC Different in pairwise msg 2 of 4-way handshake!
[JDC-1 /tmp]#
``

**Comment by messense** [comment]
看不出来什么，执行 aliyundrive-webdav 的 exit code 是什么？

**Comment by onlyJinx** [comment]
没有输出任何信息，也没有报错，就执行之后完全没反应，有什么排查方法吗🤣

**Comment by onlyJinx** [comment]
```
JDC-1 3.4.3.9-099_21-10-3]# 2021-11-08 20:36:47
[JDC-1 /opt/home/admin]# cd /tmp/
[JDC-1 /tmp]# ./aliyundrive-webdav --help
[JDC-1 /tmp]# echo $?
127
[JDC-1 /tmp]#
```

**Comment by messense** [comment]
不知道有没有 ldd 命令，执行 `ldd ./aliyundrive-webdav` 看看输出。

**Comment by onlyJinx** [comment]
```
[JDC-1 /opt/home/admin]# cd /tmp/
[JDC-1 /tmp]# ldd ./aliyundrive-webdav
ldd: can't open cache '/etc/ld.so.cache'
        not a dynamic executable
[JDC-1 /tmp]#
```

**Comment by messense** [comment]
```bash
root@XiaoQiang:/tmp# ldd aliyundrive-webdav
	/usr/lib/libc.so.1 (0x55550000)
Error loading shared library libatomic.so.1: No such file or directory (needed by aliyundrive-webdav)
Error relocating aliyundrive-webdav: __atomic_fetch_or_8: symbol not found
Error relocating aliyundrive-webdav: __atomic_load_8: symbol not found
Error relocating aliyundrive-webdav: __atomic_is_lock_free: symbol not found
```

upx 压缩导致问题被掩盖了，看起来是编译出来的二进制文件不是静态链接的了，并且依赖了 libatomic.so.1 而这个动态链接库 mipsel OpenWrt 系统中没有。

**Comment by messense** [comment]
可以先尝试一下较老的版本，一时半会也搞不清楚是什么导致的。

**Comment by onlyJinx** [comment]
你是对的，测试了一下，0.5.1可以用，再往上就不可以了。那我就等修复了，多谢了~
(v0.5.1竟然被windows报毒了)

![image](https://user-images.githubusercontent.com/21324835/140754325-bbd0613e-9fc9-46c8-8e26-b8e9082e77b9.png)

**Comment by messense** [comment]
可以试一下 0.5.5 版本：https://github.com/messense/aliyundrive-webdav/releases/tag/v0.5.5

**Comment by onlyJinx** [comment]
0.5.5版本测试后可以使用，感谢。
顺便问一下，路由器重启的话怎么重新获取token?
我现在有一个比较笨的想法就是把每次程序自动刷新出来的tokey输出到一个文件file保存起来，然后重启后再去读取整个文件(路由器重启大概一分钟，token应该还有效)，最后在```./aliyundrive-webdav --refresh-token $file```

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/issues/50#issuecomment-924834144

**Comment by onlyJinx** [comment]
nice! 重启试了一下可以重连。 原来已经有解决方法了，是我大意了没注意看文档。
