### ISSUE TITLE
N1盒子coreelec系统docker

### ISSUE THREAD

**Issue by jmheqiao** [messense/aliyundrive-webdav#15]

**Comment by messense** [comment]
什么问题？

**Comment by jmheqiao** [comment]
N1盒子昨天在openwrt系统很容易安装正常运行，今天用coreelec系统docker部署出错
CoreELEC:~ # docker run -d --name=aliyundrive-webdav --restart=unless-stopped -p 8088:8080 -e REFRESH_TOKEN='e80f06fe04
xxxxxxxxxxxxxx61637cb2' messense/aliyundrive-webdav
Unable to find image 'messense/aliyundrive-webdav:latest' locally
latest: Pulling from messense/aliyundrive-webdav
docker: no matching manifest for linux/arm/v8 in the manifest list entries.

**Comment by messense** [comment]
目前 docker 镜像没有 `linux/arm/v8` 架构的，有 `linux/arm64` 的，不太清楚这个两个有什么区别。

**Comment by jmheqiao** [comment]
另一个软件 cloudnas/clouddrive支持如下架构则顺利安装，希望大神早日运行这个架构。
Architecture | Tag
-- | --
x86-64 | amd64
arm64 | arm64
armhf | arm32

**Comment by messense** [comment]
可以 `docker inspect cloudnas/clouddrive` 看看是用的哪个架构。

**Comment by jmheqiao** [comment]
CoreELEC:~ # docker inspect cloudnas/clouddrive
[
    {
        "Id": "sha256:fb7285ed941f62c162feadf9fc011c4ad11664d0daa86c1dcd38c7e2f64cdc78",
        "RepoTags": [
            "cloudnas/clouddrive:latest"
        ],
        "RepoDigests": [
            "cloudnas/clouddrive@sha256:8804bfd8ffec00f9b5ee460d7fed10019d5849dac6a962ed52c003bc0d421f15"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-09-04T02:29:07.444322183Z",
        "Container": "4bb429f460626c1942d1d41e748536daf968592659565b4ac13cda6b7ac57a5c",
        "ContainerConfig": {
            "Hostname": "4bb429f46062",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true",
                "DOTNET_VERSION=6.0.0-preview.7.21377.19",
                "ASPNET_VERSION=6.0.0-preview.7.21378.6",
                "Logging__Console__FormatterName=Json",
                "SOURCE_DIR=/CloudDriveCore",
                "ARCH=arm32v7"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/start.sh\"]"
            ],
            "Image": "sha256:88150336cb0c9e00bdafb400aa482f9bceaec730211d21a4dc040325dd979c37",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/start.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "19.03.15",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true",
                "DOTNET_VERSION=6.0.0-preview.7.21377.19",
                "ASPNET_VERSION=6.0.0-preview.7.21378.6",
                "Logging__Console__FormatterName=Json",
                "SOURCE_DIR=/CloudDriveCore",
                "ARCH=arm32v7"
            ],
            "Cmd": null,
            "Image": "sha256:88150336cb0c9e00bdafb400aa482f9bceaec730211d21a4dc040325dd979c37",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/start.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "arm",
        "Os": "linux",
        "Size": 271570437,
        "VirtualSize": 271570437,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/25e77ebd4093d3cf428f1d97826f995bac907b57ec14c4b96fe6da0d2da967f6/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/17fb420e9310e273689f62418ddab6984fbdf90a66ce437f2113643a67d772d9/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/24bf2197981b01a3877a1bb16166b246a465045112d0f33295a7217c24e42000/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/fe5083ed90394894877ea100219fe57139e5561a55e07c6d5dc69d81657cece6/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/5fe6c00b622ade3afdb5ff05a7f6920c87ad64955fd7c97c6a47d378bb189106/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/a8da3b502364f355b5a3e03baf47078a4af361e237cdcc11f9e001d9c2071cb3/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/9b9d50b9eef2a1a668469c716aeecb401aee827611500a2833225b6bc89a5ac8/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/ba4b8bc6c80f006d2384df1e7f113107a39a044d71578ceea2f1598c0e87581f/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/eb630bfca5c7c01878ab16032d878c84797cc1481886a272420f24cfdf819d7d/diff",
                "MergedDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/3bcb24726a487dfdede03a9846724c51737df1210038390278d48b68c5bc3660/merged",
                "UpperDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/3bcb24726a487dfdede03a9846724c51737df1210038390278d48b68c5bc3660/diff",
                "WorkDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/3bcb24726a487dfdede03a9846724c51737df1210038390278d48b68c5bc3660/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:34bfe34c2628d9f914272ccd3eeab63b947c4ac71d4ad724d7cbe95cc7fe9b40",
                "sha256:1f3d23b45b63bfca86c43769af22bb4bfbbb58ad0bfbd75fc875144e490003be",
                "sha256:9ebd6478be39dfb14b648e351a9f41dad2dfefaceff896d99d8a273500a25a2b",
                "sha256:69bb2a2a8adf1f6345c333a25e28c1bbe334dcac6f968b3fd60b098935e19c87",
                "sha256:16970b49edf35a9d3a691e7cf315f4567e52b505c892a90f9914e1b84175243c",
                "sha256:343f61c21f5f07e58bae1dedc1fab451ecca14a028ed3fd52c7f03b52781fea1",
                "sha256:111e28e4f144f29499dd0967e3201a8c992efe0d993c77d8d1b792d386cc5a2f",
                "sha256:322678a981b109afa641e94e960c195cf3c2c4a9185e5be6fe61902bdcc82c84",
                "sha256:56574a590d5a06452ab37bcd1de4bfd86b80bbc96715ca830ca5d79d2ebcb175",
                "sha256:f2c723a24cb93346fded456db821119c5143349c636ed7d248c21803c35de762"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by messense** [comment]
ARCH=arm32v7 看起来是需要 linux/arm/v7 的镜像。

**Comment by jmheqiao** [comment]
啊，那暂时这个系统不能用了。

**Comment by messense** [comment]
增加了 linux/arm/v7 的 Docker 镜像，可以重新试一下。

**Comment by messense** [comment]
其实也可以试试 docker 增加参数 `--platform linux/arm64` 看起来这个盒子 CPU 是 arm64 的。

**Comment by jmheqiao** [comment]
谢谢！

**Comment by jmheqiao** [comment]
大神效率神速！现在顺利装好了，非常感谢！
