### ISSUE TITLE
这是是只有http端口访问，没其他功能是吧

### ISSUE THREAD

**Issue by aogg** [messense/aliyundrive-webdav#16]

**Comment by messense** [comment]
https://baike.baidu.com/item/WebDAV/4610909

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/132113107-19910303-b12c-48fb-b716-515c688397cb.png)
如何使用webdav

**Comment by messense** [comment]
目前不支持上传，主要是用来实现在电视上观看云盘内容的。
