### ISSUE TITLE
上传出现文件夹重复创建的情况

### ISSUE THREAD

**Issue by HengyueLi** [messense/aliyundrive-webdav#175]
### 问题描述

使用 `rclone`出现多个相同文件夹的问题。这个问题隔壁的项目也有[相同遭遇](https://github.com/zxbu/webdav-aliyundriver/issues/60)。解决办法其中也给了，就是加上`--transfers=1`。不知道这算不算一个bug。我担心加上`--transfers=1`之后会影响同步效率。

### 重现步骤

`rclone sync Dropbox remote:box`

### 版本

aliyundrive-webdav 1.0.0

### 运行平台

CentOS Linux release 7.9.2009 (Core)

### 日志

None

**Comment by messense** [comment]
Duplicated of https://github.com/messense/aliyundrive-webdav/discussions/152#discussioncomment-1649000
