### ISSUE TITLE
windows11映射网络驱动器成功，但使用potplayer播放视频报错

### ISSUE THREAD

**Issue by qq57240** [messense/aliyundrive-webdav#176]
### 问题描述

ubuntu中使用命令行为：
aliyundrive-webdav --auto-index --port=8021 --read-buffer-size=20971520 --refresh-token=我的token打码 --workdir=/etc/aliyun-webdav
windows11中使用自带的网络地址映射功能

### 重现步骤

windows中映射成本地磁盘
使用potplayer播放视频

### 版本

v1.0.0

### 运行平台

Windows 11

### 日志

无法找到该文件

该文件不存在或被锁定

**Comment by messense** [comment]
Duplicated of https://github.com/messense/aliyundrive-webdav/issues/117

Windows 请使用 RaiDrive.

**Comment by messense** [comment]
FYI, Windows 自带的 webdav 挂载功能问题非常多：https://sabre.io/dav/clients/windows/
