### ISSUE TITLE
Idea: 自动更新 OpenWrt 和梅林配置中的 refresh_token

### ISSUE THREAD

**Issue by messense** [messense/aliyundrive-webdav#18]
1. 识别运行的系统是不是 OpenWrt/Merlin
2. refresh token 之后自动更新配置文件

**OpenWrt**

```bash
uci set aliyundrive-webdav.@server[0].refresh_token 'new refresh_token'
```

**Merlin**

```bash
dbus set aliyundrivewebdav_refresh_token='new refresh_token'
```

**Comment by zhangguanzhang** [comment]
大佬，没有openwrt编译的config里=y去自动整吗

**Comment by messense** [comment]
> 大佬，没有openwrt编译的config里=y去自动整吗

什么意思？

**Comment by zhangguanzhang** [comment]
我目前是在编译openwrt的时候吧ipk文件下载放到rootfs下，通过luci的default脚本安装的。有那种config文件一件安装的吗。比如下面：
```
CONFIG_PACKAGE_luci-app-docker=y
```

**Comment by messense** [comment]
自定义 feed 就行，参考这个项目的 Release.yml 中 openwrt 编译过程。

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/commit/a69eb53a3e134f865ad99fb653dbee78e73fbee7
