### ISSUE TITLE
在浏览器中播放编解码器为: AAC, MPEG-4 Video 的视频只有声音; AAC, H.264是正常的

### ISSUE THREAD

**Issue by HKMV** [messense/aliyundrive-webdav#195]
### 问题描述

在浏览器中播放编解码器为: AAC, MPEG-4 Video 的视频只有声音; AAC, H.264是正常的

### 重现步骤

浏览器中播放编解码器为: AAC, MPEG-4 Video 的视频只有声音; AAC, H.264是正常的

### 版本

1.0

### 运行平台

N1, Armbian, Docker 

### 日志

日志一切正常

**Comment by HKMV** [comment]
补图:

编解码器为: AAC, MPEG-4 Video 的视频只有声音
![image](https://user-images.githubusercontent.com/26456469/145684120-f5be73ad-31e1-49aa-a22c-4e2f09ba2f15.png)

编解码器为: AAC, H.264 的正常
![image](https://user-images.githubusercontent.com/26456469/145684358-78b1c70a-9bbf-45b1-be7c-d5ab85eafb8a.png)

**Comment by messense** [comment]
浏览器访问不是给用户使用的，请使用 WebDAV 客户端。

**Comment by HKMV** [comment]
> 浏览器访问不是给用户使用的，请使用 WebDAV 客户端。

好吧
