### ISSUE TITLE
麻烦编译一个mips版本的

### ISSUE THREAD

**Issue by ioito** [messense/aliyundrive-webdav#22]
路由器是Newifi D2

**Comment by ioito** [comment]
好像不行，编译会报 https://github.com/briansmith/ring/pull/1277 中提到的错误

**Comment by messense** [comment]
可以试下 main 分支 `cargo build --release --no-default-features --features native-tls-vendored`

**Comment by ioito** [comment]
报错: Package `aliyundrive-webdav v0.1.22 (/home/lighthouse/aliyundrive-webdav)` does not have the feature `native-tls-vendored`

**Comment by messense** [comment]
更新下代码先。

**Comment by ioito** [comment]
![image](https://user-images.githubusercontent.com/13750250/132456299-80b614ac-1ee0-4bed-a201-a3b814fb1008.png)

现在报这个错

**Comment by messense** [comment]
Blocked on https://github.com/metrics-rs/quanta/issues/54

**Comment by messense** [comment]
mipsel 可以试试这个：https://github.com/messense/aliyundrive-webdav/suites/3709815271/artifacts/90625625

**Comment by tatsuya6502** [comment]
Hi. Moka author here. It is Moka who depends on quanta.

```
$ cargo tree -i quanta
quanta v0.9.2
└── moka v0.5.2
    └── aliyundrive-webdav v0.1.22
```

I think not only quanta has the problem on this platform but also Moka does. Let me check if I can make Moka work. I opened an issue: https://github.com/moka-rs/moka/issues/38

**Comment by messense** [comment]
@tatsuya6502 Thanks for taking a look. I've also found out that moka doesn't compile on these platforms when trying to patch quanta: https://github.com/messense/aliyundrive-webdav/runs/3541273216?check_suite_focus=true

**Comment by tatsuya6502** [comment]
Thanks for the info. Yeah. I was a kind of expecting the error. I will try to workaround it.

```
cargo build --release --target armv5te-unknown-linux-musleabi 
...

error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
  --> /root/.cargo/git/checkouts/moka-ba7e21d144061f19/03bf84e/src/sync.rs:10:30
   |
10 |         atomic::{AtomicBool, AtomicU64, Ordering},
   |                              ^^^^^^^^^
   |                              |
   |                              no `AtomicU64` in `sync::atomic`
   |                              help: a similar name exists in the module: `AtomicU8`
```

**Comment by ioito** [comment]
> mipsel 可以试试这个：https://github.com/messense/aliyundrive-webdav/suites/3713756695/artifacts/90763447

可以正常运行，麻烦release下版本，我需要重新编译下openwrt, 路由器内存太小了

**Comment by messense** [comment]
正式 release 还是等等 moka，你可以试试这个用 upx 压缩过的版本，会小很多：https://github.com/messense/aliyundrive-webdav/suites/3713970339/artifacts/90772780

**Comment by ioito** [comment]
好的，我再等等，先收悉下openwrt编译，我close这个issue了

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/releases/tag/v0.1.23
