### ISSUE TITLE
能不能帮忙编译个armv5版本

### ISSUE THREAD

**Issue by dd-gjk** [messense/aliyundrive-webdav#23]
手头有个老的设备pogoplug  pip安装不上 缺少rust  
能不能帮忙编一个armv5版本
感谢这么好的项目

**Comment by messense** [comment]
贴一下 `cat /proc/cpuinfo` 看看？

**Comment by dd-gjk** [comment]
processor       : 0
model name      : Feroceon 88FR131 rev 1 (v5l)
BogoMIPS        : 400.00
Features        : swp half thumb fastmult edsp
CPU implementer : 0x56
CPU architecture: 5TE
CPU variant     : 0x2
CPU part        : 0x131
CPU revision    : 1

**Comment by messense** [comment]
Blocked on https://github.com/metrics-rs/quanta/issues/54

**Comment by messense** [comment]
试试这个 https://github.com/messense/aliyundrive-webdav/suites/3709815271/artifacts/90625621

**Comment by tatsuya6502** [comment]
Hi. As I said on #22, I think not only quanta has the problem on this platform but also Moka does. Let me check if I can make Moka work. I opened an issue: https://github.com/moka-rs/moka/issues/38

**Comment by dd-gjk** [comment]
> 试试这个 https://github.com/messense/aliyundrive-webdav/suites/3709815271/artifacts/90625621

完美运行，感谢大佬，希望能进入日常release

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/releases/tag/v0.1.23
