### ISSUE TITLE
upx压缩后不能正常运行

### ISSUE THREAD

**Issue by ioito** [messense/aliyundrive-webdav#24]
Newifi D2 上传upx压缩后二进制，执行卡死，不返回不退出, CPU占用率一直25%

**Comment by ioito** [comment]
忽略这个问题，upx 3.96有问题，回退到3.95正常了

**Comment by messense** [comment]
https://github.com/upx/upx/issues/504

**Comment by NullYing** [comment]
upx开发分支的解决了，但是没有release
