### ISSUE TITLE
【修复】修复梅林插件的脚本不执行问题，该死的编辑器

### ISSUE THREAD

**Issue by flyhigherpi** [messense/aliyundrive-webdav#27]
放在谷歌盘了：
https://drive.google.com/drive/folders/1jI2tsRoHdkpqj42Bp4k5LcauqNfbn8H-?usp=sharing

另外，华硕路由有点抽的地方就是armv7只能用v5二进制，所以K3是用不了384的。文件名我就相应改成 
aliyundrivewebdav_armv5_0.1.23.tar
aliyundrivewebdav_armv7_0.1.23.tar
对应自己机型能用的二进制尝试吧。。。
页面加了插件版本显示。把不存在的PNG去掉了。
![image](https://user-images.githubusercontent.com/67776691/132940743-d50c711c-9188-4f31-a155-9c47598674c1.png)

**Comment by messense** [comment]
代码之前合并进来了，建议直接仓库更新下提个 PR 过来。

**Comment by messense** [comment]
>  华硕路由有点抽的地方就是armv7只能用v5二进制

这个问题可以贴一下 `cat /proc/cpuinfo` 或者这个固件对应的获取 cpu 信息的命令的输出吗？

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/commit/8a612d968eec568ed5ccc7c8ed3238a4b8a150fe

**Comment by flyhigherpi** [comment]
> 代码之前合并进来了，建议直接仓库更新下提个 PR 过来。

刚的版本WEB页面有问题，没保存对。重发了。小问题。
哈哈
https://drive.google.com/drive/folders/1jI2tsRoHdkpqj42Bp4k5LcauqNfbn8H-?usp=sharing

**Comment by flyhigherpi** [comment]
AX88U cpuinfo：
![image](https://user-images.githubusercontent.com/67776691/132941371-747ce765-8278-4813-ae5c-023b7913718d.png)
K3 cpuinfo:
![image](https://user-images.githubusercontent.com/67776691/132941383-6a43d69f-323d-4b28-bacf-9886bf661d7d.png)

**Comment by messense** [comment]
K3 那个你看看 https://github.com/messense/aliyundrive-webdav/releases/download/v0.1.24/aliyundrive-webdav-armv7-unknown-linux-musleabi.tar.gz 这个版本可以跑不？
