### ISSUE TITLE
R2S在线安装以后，界面直接变成纯英文的了！

### ISSUE THREAD

**Issue by chwl66** [messense/aliyundrive-webdav#275]
### 问题描述

使用下面的命令进行安装的`wget https://github.com/messense/aliyundrive-webdav/releases/download/v1.2.0/aliyundrive-webdav_1.2.0_aarch64_generic.ipk
wget https://github.com/messense/aliyundrive-webdav/releases/download/v1.2.0/luci-app-aliyundrive-webdav_1.2.0_all.ipk
wget https://github.com/messense/aliyundrive-webdav/releases/download/v1.2.0/luci-i18n-aliyundrive-webdav-zh-cn_1.2.0-1_all.ipk
opkg install aliyundrive-webdav_1.2.0_aarch64_generic.ipk
opkg install luci-app-aliyundrive-webdav_1.2.0_all.ipk
opkg install luci-i18n-aliyundrive-webdav-zh-cn_1.2.0-1_all.ipk`
![image](https://user-images.githubusercontent.com/58024471/151148530-f955e671-cc6f-401b-9c1b-4b76be04c6ea.png)

### 重现步骤

无

### 版本

1.2.0

### 运行平台

r2s

### 日志

没有日志！

**Comment by messense** [comment]
不知道为啥，重装下 zh-cn 的系统语言包应该就可以恢复了。
