### ISSUE TITLE
云服务器 rclone挂载后上传大文件失败

### ISSUE THREAD

**Issue by geekhuashan** [messense/aliyundrive-webdav#276]
### 问题描述

用rclone 挂载在阿里云轻量服务器上，之后用rclone 命令复制上传到云盘，小文件可以 5M左右的，

大文件没有成功过

明明是267M的文件，随着上传，Transferred 那边总大小会 变成 已上传的量+267M

导致永远上传不完

已尝试Transferred 超过300M，还是不行

![image](https://user-images.githubusercontent.com/47098938/151278530-8f9c1687-a813-4e51-9f52-ba3855087876.png)

### 重现步骤

docker 安装
rclone 挂载
rclone 上传

### 版本

最新docker版

### 运行平台

linux

### 日志

HTTP status client error (400 Bad Request) for url (https://api.aliyundrive.com/v2/recyclebin/trash)

**Comment by geekhuashan** [comment]
后来换了 https://github.com/zxbu/webdav-aliyundriver 挂载之后rclone 上传成功，其他都没有动。
能看看是什么地方的问题吗

![image](https://user-images.githubusercontent.com/47098938/151288324-0d264042-7582-440c-a6bd-9bd1f2f8a0a7.png)
![image](https://user-images.githubusercontent.com/47098938/151288971-dc77aed8-1d03-45fd-b829-29b899a91fe5.png)

**Comment by messense** [comment]
docker 部署的可以用 `docker logs` 命令看日志。

https://docs.docker.com/engine/reference/commandline/logs/

**Comment by raydoom** [comment]
2022-02-28T13:06:27.480805Z ERROR aliyundrive_webdav::vfs: upload file chunk 474 failed file_id=621cbabdb1cb42822f6444d8ab08df37c4101671 file_name=[终结者2：审判日]Terminator.2.Judgment.Day.1991.2160p.Blu-ray.H265.2Audio.DTS-HD.MA.5.1.BOBO.mkv size=18933715783 error=HTTP status client error (403 Forbidden) for url (https://bj29.cn-beijing.data.alicloudccp.com/4V2XckmS%2F1196115%2F621cbabdb1cb42822f6444d8ab08df37c4101671%2F621cbabdde1fb59c19a44feaab97335bb27052e7?partNumber=474&uploadId=A87B7CEEB6844EEDB8C52119592AD448&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1646053581&x-oss-signature=PYXkBm5qQ9FzlzTuXz7Jr%2FlQgPLOVCpKyPusznCoVss%3D&x-oss-signature-version=OSS2)

**Comment by raydoom** [comment]
上传小文件没问题，docker版本，镜像已经是最新了，使用winscp和raidrive都是这样

**Comment by zhudan** [comment]
+1我也遇到这个问题

**Comment by snow212-cn** [comment]
我的非docker环境也遇到了，上传大文件每次100%后报错，transfered总量加一倍，无限循环

**Comment by snow212-cn** [comment]
自己研究出的解决办法： `--multi-thread-streams 0`，禁用多线程，默认4线程最后合并出错

**Comment by geekhuashan** [comment]
查看日志显示这个，HTTP status client error (400 Bad Request) for url (https://api.aliyundrive.com/v2/recyclebin/trash)

大佬怎么弄阿

**Comment by messense** [comment]
`400 Bad Request` fixed in 733bfd2385f8b3ee98279b8012a054dcd5112f17

**Comment by messense** [comment]
`403 Forbidden` is tracked in #307

**Comment by geekhuashan** [comment]
> `400 Bad Request` fixed in [733bfd2](https://github.com/messense/aliyundrive-webdav/commit/733bfd2385f8b3ee98279b8012a054dcd5112f17)

我这边还是有问题，

![image](https://user-images.githubusercontent.com/47098938/178927107-6b23f126-cc0b-4383-bcf0-76a906640622.png)

**Comment by messense** [comment]
`docker run --rm -it messense/aliyundrive-webdav aliyundrive-webdav --version` 看下版本。

**Comment by geekhuashan** [comment]
看到了 1.7.3
不好意思啊。

我是小白，昨天看到更新之后 重置了服务器完全新安装了docker image TAG显示latest。

怎么可以更新docker image 到最新啊

**Comment by messense** [comment]
可以直接用 `messense/aliyundrive-webdav:1.7.4`

**Comment by geekhuashan** [comment]
> 可以直接用 `messense/aliyundrive-webdav:1.7.4`

已完美解决，谢谢大佬
