### ISSUE TITLE
希望增加32位openwrt x86的预编译版本

### ISSUE THREAD

**Issue by islercn** [messense/aliyundrive-webdav#28]
虽然文件都有，但是不用每次自己编译还是更好的，先谢过了！

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/suites/3744478594/artifacts/91850851

可以试一下，以后的发布中会包含这个。

**Comment by messense** [comment]
是用 https://downloads.openwrt.org/snapshots/targets/x86/generic/openwrt-sdk-x86-generic_gcc-10.3.0_musl.Linux-x86_64.tar.xz 这个 SDK 构建的，不知道是否能满足你的运行环境需求。

**Comment by islercn** [comment]
没有问题，感谢！
