### ISSUE TITLE
在仅有ipv6单栈的服务器上运行报错

### ISSUE THREAD

**Issue by karma-sun** [messense/aliyundrive-webdav#280]
### 问题描述

在仅有ipv6单栈的服务器上运行，会报错Network unreachable,但直接ping报错的域名websv.aliyundrive.com并无异常

### 重现步骤

1. 服务器仅设置ipv6地址，无ipv4
2. 启动程序:aliyundrive-webdav -r XXX

### 版本

1.2.1

### 运行平台

ubuntu20

### 日志

WARN aliyundrive_webdav::drive: refresh token failed, will wait and retry error=error sending request for url (https://websv.aliyundrive.com/token/refresh): error trying to connect: tcp connect error: Network unreachable (os error 101)

**Comment by messense** [comment]
`curl -v https://websv.aliyundrive.com/token/refresh` 呢？

**Comment by karma-sun** [comment]
> `curl -v https://websv.aliyundrive.com/token/refresh` 呢？

可以获得json响应
*   Trying 2001:67c:2b0:db32:0:1:65c8:7d02:443...
* TCP_NODELAY set
*   Trying 101.200.125.2:443...
* TCP_NODELAY set
* Immediate connect fail for 101.200.125.2: Network is unreachable
* Connected to websv.aliyundrive.com (2001:67c:2b0:db32:0:1:65c8:7d02) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=CN; ST=ZheJiang; L=HangZhou; O=Alibaba (China) Technology Co., Ltd.; CN=*.aliyundrive.com
*  start date: Apr 20 03:16:06 2021 GMT
*  expire date: May 22 03:16:06 2022 GMT
*  subjectAltName: host "websv.aliyundrive.com" matched cert's "*.aliyundrive.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - SHA256 - G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55c158a12db0)
> GET /token/refresh HTTP/2
> Host: websv.aliyundrive.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 405 
< access-control-allow-credentials: true
< access-control-expose-headers: Content-MD5,X-Request-Id,X-Canary,X-Share-Token,X-Ca-Request-Id,X-Ca-Error-Code,X-Ca-Error-Message
< content-type: application/json;charset=UTF-8
< date: Sun, 30 Jan 2022 09:49:49 GMT
< vary: Origin
< x-canary: product=adrive
< x-request-id: 55e563ac-f0e0-4bf6-9f43-6e8398f254f8
< content-length: 125
< 
* Connection #0 to host websv.aliyundrive.com left intact
{"code":"MethodNotAllowed","message":"Request method 'GET' not supported","requestId":"55e563ac-f0e0-4bf6-9f43-6e8398f254f8"}

**Comment by karma-sun** [comment]
又试了一下，可以正常运行了
