### ISSUE TITLE
Windows11自带的webdav客户端无法连接

### ISSUE THREAD

**Issue by mgy-qyqf** [messense/aliyundrive-webdav#291]
### 问题描述

Windows11自带的webdav客户端无法连接，
![image](https://user-images.githubusercontent.com/73788063/153334603-3afa8be9-1861-4b11-ace7-f144c96f76ba.png)
我已经获取了token，aliyundrive-webdav运行正常。
![2022-02-10 (2)](https://user-images.githubusercontent.com/73788063/153335041-418376d3-d451-428b-8a08-aab9ddfad5a8.png)

### 重现步骤

运行aliyundrive-webdav，在Windows资源管理器里添加网络位置

### 版本

aliyundrive-webdav 1.2.2

### 运行平台

Windows11

### 日志

C:\Users\孟古一>aliyundrive-webdav -r xxx -p 5005
2022-02-10T03:59:24.769199Z  INFO aliyundrive_webdav::drive: refresh token succeed refresh_token=xxx nick_name=mengguyi
2022-02-10T03:59:24.769461Z  INFO aliyundrive_webdav::drive: found default drive drive_id=205561420
2022-02-10T03:59:24.770619Z  INFO aliyundrive_webdav: listening on http://0.0.0.0:5005

**Comment by messense** [comment]
不建议使用 Windows 自带的功能，非常垃圾。https://github.com/messense/aliyundrive-webdav/issues/117

建议使用 RaiDrive.

**Comment by XiaoSeee** [comment]
Windows11自带的需要HTTPS链接，HTTP的不。

**Comment by mgy-qyqf** [comment]
> > Windows11自带的需要HTTPS链接，HTTP的不。
> 
> 可以 ![image](https://user-images.githubusercontent.com/73788063/154033310-70ebb455-1a36-487e-8eac-a30ae4b4b3d7.png) 之前是我设置错了，但Windows自带的是真垃圾

前提是webdav端口开在回环地址上

**Comment by yin1999** [comment]
Windows自带的webdav使用BasicAuth的话默认需要 `https`。如果想在 `http` 协议下正常挂载 webdav，需要修改注册表并在服务中重启 `WebClient`。

注册表记录为：`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters` 下的 `BasicAuthLevel` 将其改为十进制下的 `2` 即可正常使用（类型为 `DWORD`）。

![image](https://user-images.githubusercontent.com/15844309/156287803-0aee085b-46bf-4e8e-a26d-7f3c15746f98.png)

![image](https://user-images.githubusercontent.com/15844309/156287862-685b2a11-10ca-43a6-8662-51c9783cb6f2.png)
