### ISSUE TITLE
能搞个梅林386的么

### ISSUE THREAD

**Issue by coderykw** [messense/aliyundrive-webdav#3]
多谢

**Comment by messense** [comment]
[aliyundrivewebdav-merlin-arm380.tar.gz](https://github.com/messense/aliyundrive-webdav/files/7070050/aliyundrivewebdav-merlin-arm380.tar.gz)

可以试一下这个包。

**Comment by coderykw** [comment]
能装了！！！

**Comment by coderykw** [comment]
无法保存配置

**Comment by messense** [comment]
> 无法保存配置

是后台界面有什么报错吗？需要提供下截图，最好能给下浏览器审查元素 console 中的报错信息。

**Comment by coderykw** [comment]
![image](https://user-images.githubusercontent.com/16605891/131222887-dafaabbc-73b4-4ceb-86b9-35db00222220.png)
![image](https://user-images.githubusercontent.com/16605891/131222895-88a5d123-7ad4-4714-a900-482126fffdbb.png)

**Comment by coderykw** [comment]
![image](https://user-images.githubusercontent.com/16605891/131222975-2e856824-906a-4e2e-af65-eb83c4eafb00.png)

**Comment by messense** [comment]
可以先 ssh 登录用 dbus 手工配置下 refresh_token：

```bash
dbus set aliyundrivewebdav_refresh_token 'xxx'
dbus set aliyundrivewebdav_port 8080
# 其他类推 aliyundrivewebdav_port_auth_user 、aliyundrivewebdav_auth_password、aliyundrivewebdav_read_bufffer_size
```

**Comment by coderykw** [comment]
admin@RT-AC3100-9D4C:/tmp/home/root# dbus set aliyundrivewebdav_enable=1
admin@RT-AC3100-9D4C:/tmp/home/root# dbus set aliyundrivewebdav_port=8080
admin@RT-AC3100-9D4C:/tmp/home/root# dbus set aliyundrivewebdav_auth_user=admin
admin@RT-AC3100-9D4C:/tmp/home/root# dbus set aliyundrivewebdav_auth_password=admin
admin@RT-AC3100-9D4C:/tmp/home/root# dbus set aliyundrivewebdav_read_bufffer_size=10485760
admin@RT-AC3100-9D4C:/tmp/home/root# /koolshare/scripts/aliyundrivewebdav_config.sh
killall: aliyundrive-webdav: no process killed
2021年08月28日 23:47:29: 添加nat-start触发事件...

**Comment by messense** [comment]
看起来没啥问题？`ps | grep aliyundrive` 看下是不是跑起来了。

**Comment by coderykw** [comment]
6376 admin     1460 S    grep aliyundrive  能看到 http://192.168.50.1:8080/访问拒绝

**Comment by messense** [comment]
贴一下 `/tmp/aliyundrivewebdav.log` 日志吧。

**Comment by coderykw** [comment]
error: Found argument 'set' which wasn't expected, or isn't valid in this context

USAGE:
    aliyundrive-webdav --host <host> --port <port> --read-buffer-size <read-buffer-size> --refresh-token <refresh-token>

For more information try --help
~
~
~
~
~
- aliyundrivewebdav.log 1/6 16%

**Comment by coderykw** [comment]
可以了啊哈哈哈

**Comment by coderykw** [comment]
dmin@RT-AC3100-9D4C:/tmp# touch aliyundrivewebdav.log
^[[2mAug 28 16:47:18.107^[[0m ^[[32m INFO^[[0m aliyundrive_webdav::drive: refresh token succeed refresh_token=’xxxxxxx‘
^[[2mAug 28 16:47:18.108^[[0m ^[[32m INFO^[[0m aliyundrive_webdav::drive: found default drive id drive_id=1140396
^[[2mAug 28 16:47:18.108^[[0m ^[[32m INFO^[[0m aliyundrive_webdav: listening on 0.0.0.0:8081
~

=
- aliyundrivewebdav.log 1/3 33%
![image](https://user-images.githubusercontent.com/16605891/131225045-510802c6-79a0-4dfa-80a7-39d6a1963851.png)输入账号密码 一直不让进

**Comment by messense** [comment]
应该是 dbus 配置的问题，可以 `dbus list aliyundrivewebdav` 看下配置的账密。

BTW，用浏览器访问这个界面没有什么用处，需要用 WebDAV 客户端访问比如 [Infuse](https://firecore.com/infuse)，参考 https://github.com/messense/aliyundrive-webdav/issues/6

**Comment by coderykw** [comment]
infuse 成了！！！！！

**Comment by coderykw** [comment]
我infuse 点播阿里云 漫威4k的26g电影 网速只有3m/s 看一会卡一会

**Comment by coderykw** [comment]
![image](https://user-images.githubusercontent.com/16605891/131226812-aa6e77dc-075d-44bf-b5e4-6c726a5e73fa.png)

**Comment by messense** [comment]
384/386 固件配置方法更新到 README 上了：https://github.com/messense/aliyundrive-webdav#koolshare-%E6%A2%85%E6%9E%97%E5%9B%BA%E4%BB%B6

**Comment by messense** [comment]
可以试下 https://github.com/messense/aliyundrive-webdav/releases/tag/v0.1.20

**Comment by coderykw** [comment]
> 可以试下 https://github.com/messense/aliyundrive-webdav/releases/tag/v0.1.20

运行提交 卡住不动.。。

**Comment by coderykw** [comment]
阿里云盘服务启用中 ...
请等待日志显示完毕，并出现自动关闭按钮！
在此期间请不要刷新本页面，不然可能导致问题！

**Comment by messense** [comment]
可以看看这个 `/tmp/upload/aliyundrivewebdavconfig.log` 日志文件里面有没有什么报错信息。

**Comment by coderykw** [comment]
2018年05月05日 13:05:14: 当前已进入aliyundrivewebdavconfig.sh执行
BBABBBBC
BBABBBBC

**Comment by messense** [comment]
cc @flyhigherpi
