### ISSUE TITLE
Docker版在群晖上的问题，求解！

### ISSUE THREAD

**Issue by alvazhang79** [messense/aliyundrive-webdav#30]
9月11日下载的Docker版本，与群晖cloud sync配合（cloudsync设置单项上传），目录同步完成后。再次向群晖需要上传的目录中保存文件后，cloudsync会重复上传保存文件的那个目录下的文件，不会停。请问，这问题有办法解决吗？

**Comment by messense** [comment]
issue 提错仓库了？这个并不支持上传文件。你是用的 https://github.com/zxbu/webdav-aliyundriver 这个？

**Comment by alvazhang79** [comment]
不好意思，是没有熟悉本库。没有注意到本库不支持上传。我之前用来下载我的资料夹，使用没有问题，后来改为上传就出现上面的问题。
