### ISSUE TITLE
用客户端下载文件时服务端报错builder error: relative URL without a base

### ISSUE THREAD

**Issue by karma-sun** [messense/aliyundrive-webdav#320]
### 问题描述

用客户端下载文件时，如果要下载的文件中存在部分文件被阿里屏蔽，服务端会报错builder error: relative URL without a base，而客户端会被卡住
对这样的情况建议返回HTTP403给客户端，因为阿里会毫无征兆的突然屏蔽文件

### 重现步骤

用客户端下载一个文件夹，文件夹中预先放一个被阿里屏蔽的文件

### 版本

1.2.5

### 运行平台

Windows

### 日志

2022-03-11T02:26:35.164041Z ERROR aliyundrive_webdav::vfs: download file failed url= error=builder error: relative URL without a base

**Comment by messense** [comment]
什么客户端？

**Comment by messense** [comment]
@lazymartin 等 https://github.com/messense/aliyundrive-webdav/actions/runs/2051266527 这里构建完了下载下对应的版本，跑的时候加上 `--debug` 参数，再重试下贴一下更详细的日志。

**Comment by messense** [comment]
@lazymartin 复现了这个问题，原因是阿里云盘接口对于 iOS Live Photo 格式 .livp 没有返回下载地址。
