### ISSUE TITLE
v0.1.25 可以上传了么？

### ISSUE THREAD

**Issue by Calmact** [messense/aliyundrive-webdav#33]
能够新建文件夹，但是不能上传文件，x86_64版本

**Comment by messense** [comment]
不能。

Duplicate of https://github.com/messense/aliyundrive-webdav/issues/1

**Comment by Goooooooooood** [comment]
特地注册了账号来发言。

通过NetDrive挂载云盘为本地磁盘后，上传文件提示“磁盘写保护”。

我平时也会使用nplayer&infuse，没错，这些播放器是把元数据存在播放端的，不需要写入文件至阿里云盘。但像emby这类媒体管理程序，自动下载影片海报、缩略图，保存放进度信息等等，是需要写入文件至影片目录的。

如果能解决上传/写入问题，那真的就太棒了。感恩。

目前使用另一位作者的.jar工具，是可以实现上传/写入功能的，但是程序运行效率有问题，所以会持续关注本程序。谢谢。
