### ISSUE TITLE
手机播放也太慢了吧？

### ISSUE THREAD

**Issue by chancat87** [messense/aliyundrive-webdav#35]
![Screenshot_2021-09-14-03-17-43-89_79350d495578c0ed37372bf4f264524a](https://user-images.githubusercontent.com/25543219/133143607-94492c54-dedc-4330-bdf6-6fd2223f1f28.jpg)
老是这样啊，是我个人的问题嘛？安卓机用的nplay，需要设置什么嘛各位？

**Comment by messense** [comment]
手机为啥不用官方客户端？

**Comment by raydoom** [comment]
我苹果手机，用nplayer连的webdav，播放4k没问题，很流畅

**Comment by messense** [comment]
看 loading 的信息是 rebuild font cache （重建字体缓存）看起来和视频加载速度没关系，issue 先 close 了。
