### ISSUE TITLE
运行报错：HTTP status client error (400 Bad Request)

### ISSUE THREAD

**Issue by scdx26** [messense/aliyundrive-webdav#37]
在Linux下运行：
./aliyundrive-webdav --refresh-token "be7da06468714f798xxxxxxxxxxxxxxxxxx"

分别在arm和mips架构下测试都报如下错误：

Sep 14 12:24:50.187 ERROR aliyundrive_webdav::drive: refresh token failed: HTTP status client error (400 Bad Request) for url (https://websv.aliyundrive.com/token/refresh)
Error: initialize aliyundrive file system failed

**Comment by messense** [comment]
通常是 refresh token 过期了。

**Comment by scdx26** [comment]
因为在clouddrive中正常使用到的，没怀疑是因为过期了。重新获取了就运行正常了，谢谢你提供了这么好的工具，还编译了各种架构。非常感谢。
