### ISSUE TITLE
子目录创建文件夹不能和根目录文件重名，推测是缓存问题

### ISSUE THREAD

**Issue by gitLinan** [messense/aliyundrive-webdav#379]
### 问题描述

在子目录下创建新的文件夹，如果和根目录的文件夹有重名的则会失败。

### 重现步骤

前置条件

我的阿里云盘文件解构假设如下
---A
---B
   |---D
---C

在B的子目录创建A和C均会提示失败

### 版本

aliyundrive-webdav 1.3.1

### 运行平台

Docker

### 日志

![image](https://user-images.githubusercontent.com/33097694/162702318-af5f1f8d-180b-4c65-85d1-ecb89e8016df.png)

**Comment by gitLinan** [comment]
我使用macos的Transmit也有这样的问题。。。

**Comment by gitLinan** [comment]
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/33097694/164965804-9b1570f3-5616-436a-926c-b08ea8a15ea9.png">

根目录有一个电影文件夹如果我在二级目录再创建一个电影的话 刷新就会显示未命名的文件夹 看日志应该是说名字冲突了

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/33097694/164965875-678d44bf-96d2-4f4e-a5ab-9b054aa55fa7.png">

**Comment by heyrict** [comment]
复现步骤 (Archlinux aliyundrive-webdav=v1.3.3)

```sh
❯ mkdir -p A B/A C/B/A && touch A/D.txt B/A/D.txt C/B/A/D.txt
❯ rclone copy A aliyun_local:/
❯ rclone copy B aliyun_local:/ # 这一步骤 rclone 返回成功，但文件并未上传
❯ rclone copy C aliyun_local:/
<3>ERROR : B/A/D.txt: Failed to copy: 409 Conflict
<3>ERROR : Attempt 1/3 failed with 1 errors and: 409 Conflict
<3>ERROR : B/A/D.txt: Failed to copy: 409 Conflict
<3>ERROR : Attempt 2/3 failed with 1 errors and: 409 Conflict
<3>ERROR : B/A/D.txt: Failed to copy: 409 Conflict
<3>ERROR : Attempt 3/3 failed with 1 errors and: 409 Conflict
Failed to copy: 409 Conflict
```

此外实际使用时还存在 `Failed to copy: Update mkParentDir failed: 409 Conflict` 和 `Failed to copy: object not found`等错误，也可能与之有关。

**Comment by messense** [comment]
@heyrict 加上 `--debug` 参数跑 aliyundrive-webdav ，贴一下相关的日志。

**Comment by messense** [comment]
macOS 下 ForkLift 应用复现失败。

**Comment by messense** [comment]
建议试试新版本，如果还有问题请重新开 issue.
