### ISSUE TITLE
手机应用code editor, quickeditor 无法使用webdav服务

### ISSUE THREAD

**Issue by zongou** [messense/aliyundrive-webdav#385]
### 问题描述

如标题，图1是code editor的错误提示，图二是网页response，图三表示在文件管理器里可以正常使用
![Screenshot_2022-04-13-18-29-47-457_com rhmsoft edit pro](https://user-images.githubusercontent.com/23202896/163170622-56db8eea-735f-456a-9e3d-b5ae34bb0879.jpg)
![Screenshot_2022-04-13-19-24-15-973_com termux](https://user-images.githubusercontent.com/23202896/163170677-a1fb6085-1bf7-4cf1-b16b-b48eb61decdf.jpg)
![Screenshot_2022-04-13-19-25-37-643_com lonelycatgames Xplore](https://user-images.githubusercontent.com/23202896/163170720-5e78d07d-a932-40be-baac-14c09238c038.jpg)

### 重现步骤

1：运行 aliyundrive-webdav, 以下运行命令
./aliyundrive-webdav -r $(cat /sdcard/aliyundrive_refresh_token) -U admin -W admin -p1688 --host localhost
2：code editor里添加
3：app报错, 图一

### 版本

v1.3.1

### 运行平台

termux, android 10, arm64

### 日志

HTTP/1.1 405 Method Not Allowed
content-length: 0
connection: close                                       date: Wed, 13 Apr 2022 11:24:05 GMT

**Comment by messense** [comment]
不会支持这种使用场景。
