### ISSUE TITLE
OpenWrt SNAPSHOT r19480-45b3111b99 / LuCI Master git-22.089.43958-7110635  luci error

### ISSUE THREAD

**Issue by phoenix13023** [messense/aliyundrive-webdav#394]
### 问题描述

如题所写，我这是刚刚完成3个安装包的install：
[aliyundrive-webdav_1.3.1-1_x86_64.ipk]
[luci-app-aliyundrive-webdav_1.3.1_all.ipk]
[luci-i18n-aliyundrive-webdav-zh-cn_1.3.1-1_all.ipk]

在用的openwrt也是新安装的一个X86 snapshot版本OpenWrt SNAPSHOT r19480-45b3111b99 / LuCI Master git-22.089.43958-7110635

点击openwrt图形页面的 aliyundrive webdav页面，显示下面错误内容：
/usr/lib/lua/luci/dispatcher.lua:1374: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1374: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1051: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:1027: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

### 重现步骤

1、下载3个安装 ipk文件
2、opkg install 个ipk文件，显示成功
3、重启openwrt
4、点击aliyundrive webdav 的图形页面，显示上述错误。

### 版本

1.3.1-1

### 运行平台

OpenWrt SNAPSHOT r19480-45b3111b99 / LuCI Master git-22.089.43958-7110635

### 日志

/usr/lib/lua/luci/dispatcher.lua:1374: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1374: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1051: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:1027: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by messense** [comment]
系统问题吧，试试 

```bash
opkg update
opkg install luci luci-base luci-compat
```

**Comment by phoenix13023** [comment]
的确，缺少了 luci-compat 这个包。
