### ISSUE TITLE
资源占用挺高的

### ISSUE THREAD

**Issue by eritpchy** [messense/aliyundrive-webdav#4]
RT
STARED
感谢您的付出
![AB8786C984169488782BD0CC37CD8098](https://user-images.githubusercontent.com/8630635/130910076-265e8b9f-09fb-426e-9cf6-3756591fd290.jpg)
![726FDC30E053541A28C58290A0D11E22](https://user-images.githubusercontent.com/8630635/130910088-67c78c54-a325-43b7-b1e6-f11a92843195.jpg)
![ED123908DE1E487B1E9E91594A3DF283](https://user-images.githubusercontent.com/8630635/130910099-56895e03-9855-4654-9dea-ffff5923229e.jpg)

**Comment by messense** [comment]
[v0.1.13](https://github.com/messense/aliyundrive-webdav/releases/tag/v0.1.13) 版本对内存占用做了一些优化，资源占用应该会降低不少，可以试一下。
