### ISSUE TITLE
请问如何让docker自动更新refresh_token值呢？

### ISSUE THREAD

**Issue by rewei** [messense/aliyundrive-webdav#40]
请问如何让docker自动更新refresh_token值呢？

**Comment by messense** [comment]
refresh_token 默认就是自动更新的，只是不会反映到环境变量中，不重启容器的话一般不会有问题，重启容器可能需要重新提供一个新的 refresh_token

**Comment by liujixu1984** [comment]
不可以直接更新到配置文件/etc/config/aliyundrive-webdav里面去吗 这样就省很多事了

**Comment by messense** [comment]
Implemented in main branch.
