### ISSUE TITLE
不能用，插件版本都显示不了

### ISSUE THREAD

**Issue by qg888** [messense/aliyundrive-webdav#41]
![image](https://user-images.githubusercontent.com/85546951/133701893-18eb76d5-967d-4afc-a490-fe1435a90a89.jpeg)![image](https://user-images.githubusercontent.com/85546951/133701907-d9566bbe-be56-4345-8e3f-96365efbccb0.jpeg)![image](https://user-images.githubusercontent.com/85546951/133701945-4f8eb116-ca74-479e-9d21-791017756dd9.jpeg)

**Comment by wkgr2009** [comment]
我的梅林也是这样

**Comment by messense** [comment]
贴一下 `/tmp/upload/aliyundrivewebdav.log` 完整日志，注意脱敏 access_token 。

**Comment by qg888** [comment]
> 贴一下 `/tmp/upload/aliyundrivewebdav.log` 完整日志，注意脱敏 access_token 。

![image](https://user-images.githubusercontent.com/85546951/133714958-7cae17cd-07e2-4c42-b27b-d8fead70e4c0.png)

**Comment by qg888** [comment]
许可被拒绝![image](https://user-images.githubusercontent.com/85546951/133716476-7a2b382a-8c96-4f51-929a-3fe8c03294f4.png)> 贴一下 `/tmp/upload/aliyundrivewebdav.log` 完整日志，注意脱敏 access_token 。

**Comment by messense** [comment]
@qg888 这个是个文本文件。。。你 `cat /tmp/upload/aliyundrivewebdav.log`...

**Comment by qg888** [comment]
> @qg888 这个是个文本文件。。。你 `cat /tmp/upload/aliyundrivewebdav.log`...

![image](https://user-images.githubusercontent.com/85546951/133717370-eb151e7c-a870-4859-868e-2a26982fc2d4.png)

**Comment by messense** [comment]
refresh token 不对，重新获取。

![image](https://user-images.githubusercontent.com/1556054/133717720-35fbb24e-9dc7-4dd2-8304-da6c5a538368.png)

应该是图中红色抹去部分内容。

**Comment by qg888** [comment]
是这个，但是就是启动不了阿里云盘WebDAV

**Comment by messense** [comment]
可能过期了。https://github.com/messense/aliyundrive-webdav/issues/37

**Comment by qg888** [comment]
重新获取了refresh token还是没用

**Comment by qg888** [comment]
弄好了，这次网页弄的refresh token有用，原先我一直app抓包的refresh token没用

**Comment by wkgr2009** [comment]
怎么弄的，我在阿里云盘网页按下f12 找到的refresh token填进去，说参数错误。
