### ISSUE TITLE
建议添加挂载路径，方便多帐号使用

### ISSUE THREAD

**Issue by 4860575** [messense/aliyundrive-webdav#42]
如果能添加挂载路径选项就完美了，这样可以同时使用多个账号。例如：https://github.com/zxbu/webdav-aliyundriver项目里的“--aliyundrive.work-dir=/etc/aliyun-driver/”

**Comment by messense** [comment]
不需要，不依赖本地文件。

**Comment by 4860575** [comment]
> 不需要，不依赖本地文件。

那如何挂载多个账号呢？

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav#命令行用法

不同账号用不同端口就行了。
