### ISSUE TITLE
aarch64.ipk安装失败（架构不兼容）

### ISSUE THREAD

**Issue by vonl1** [messense/aliyundrive-webdav#44]
路由器型号：小米ax3600,openwrt固件使用的是：https://github.com/Boos4721/updater/tree/OpenWrt

命令行输出：
2021-09-18 20:31:20 (7.84 MB/s) - 'aliyundrive-webdav_0.1.27-1_aarch64_generic.ipk' saved [2122875/2122875]

root@OpenWrt:~# opkg install aliyundrive-webdav_0.1.27-1_aarch64_generic.ipk 
Unknown package 'aliyundrive-webdav'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for aliyundrive-webdav found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package aliyundrive-webdav.
 
root@OpenWrt:~# uname -m
aarch64

**Comment by messense** [comment]
opkg print-architecture 看下

**Comment by vonl1** [comment]
root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch aarch64_cortex-a53 10

**Comment by messense** [comment]
可以先修改下 /etc/opkg.conf 增加

```
arch all 1
arch noarch 1
arch aarch64_cortex-a53 10
arch aach64_generic 100
```

再安装。

**Comment by vonl1** [comment]
vim /etc/opkg.conf 文件内容如下：

dest root /                                                                         
dest ram /tmp                                                                       
lists_dir ext /var/opkg-lists                                                       
option overlay_root /overlay                                                        
option check_signature                                                              
                                                                                    
arch all 1                                                                          
arch noarch 1                                                                       
arch aarch64_cortex-a53 10                                                          
arch aach64_generic 100                                                             

然后安装的时候还是同样的问题

**Comment by messense** [comment]
上面有个错别字，应该是 `arch aarch64_generic 100` 少了个 r

**Comment by vonl1** [comment]
好的，安装成功，谢谢开发者

**Comment by messense** [comment]
aarch64_cortex-a53 加了 https://github.com/messense/aliyundrive-webdav/releases/download/v0.1.27/aliyundrive-webdav_0.1.27-1_aarch64_cortex-a53.ipk
