### ISSUE TITLE
将来有添加“上传/写入功能”的计划吗？

### ISSUE THREAD

**Issue by Goooooooooood** [messense/aliyundrive-webdav#45]
特地注册了账号来发言。

通过NetDrive挂载云盘为本地磁盘后，上传文件提示“磁盘写保护”。

我平时也会使用nplayer&infuse，没错，这些播放器是把元数据存在播放端的，不需要写入文件至阿里云盘。但像emby这类媒体管理程序，自动下载影片海报、缩略图，保存放进度信息等等，是需要写入文件至影片目录的。

如果能解决上传/写入问题，那真的就太棒了。

目前使用另一位作者的.jar工具，是可以实现上传/写入功能的，但是程序运行效率有问题，所以会持续关注本程序。

谢谢，感恩。

**Comment by messense** [comment]
> 但像emby这类媒体管理程序，自动下载影片海报、缩略图，保存放进度信息等等，是需要写入文件至影片目录的。

应该可以配置将元数据保存在单独的目录中，比如 Jellyfin 是可以的 https://forum.jellyfin.org/t/metadata-in-separate-folder/2796 ，个人觉得这类元数据不适合保存在阿里云盘中，会导致云盘内容比较混乱。

短期没有开发计划。Closing as duplicated of #1
