### ISSUE TITLE
挂载后目录无法同步

### ISSUE THREAD

**Issue by KITblue** [messense/aliyundrive-webdav#468]
### 问题描述

挂载倒本地后，如果阿里云盘内目录有增加或者减少，本地挂载的却无法同步，必须断开，然后重新挂载才能更新目录

### 重现步骤

1.开启docker，运行aliyundrive-webdav ；
2成功.挂载webdav
3.登录web阿里云盘增加目录
4.在nas文件管理器，进入webdav目录下，查看或者刷新，目录没有更新
5.断开webdav，再打开，无法连接
6.删除原webdav，重新建立webdav连接，成功连接。目录成功更新

### 版本

最新

### 运行平台

威联通NAS

### refresh token 获取方式

网页

### 日志

无。

**Comment by messense** [comment]
Duplicate of #5
