### ISSUE TITLE
群晖上部署，使用一段时间后，会出现“同步文件不存在”

### ISSUE THREAD

**Issue by flyxj** [messense/aliyundrive-webdav#469]
### 问题描述

最近换咱们的这个docker版本部署在群晖里面，刚开始一切都正常，但是过一段时间后，会出现“同步文件夹不存在”，重启也无效，日志里面的token应该也没有失效，只能取消了重新设置，还是很不方便，有人了解什么原因嘛？
<img width="665" alt="1" src="https://user-images.githubusercontent.com/1892385/176817679-5be17cf6-6057-4a41-a99a-14924c856ae1.png">

### 重现步骤

运行几天后会出现这个问题，确认文件夹其实都还在的。

### 版本

1.5.0及多个版本都有这个现象

### 运行平台

群晖7.0 docker 

### refresh token 获取方式

网页版

### 日志

![图像 001](https://user-images.githubusercontent.com/1892385/176817641-37ce71bc-82db-4f32-8dc4-1edb0b86f632.jpg)

**Comment by messense** [comment]
没有群晖帮不了你，可以自行 debug 配置 `RUST_LOG=aliyundrive_webdav=debug` 环境变量获取更详细的日志。

或者[赞助我买个群晖](https://github.com/messense/aliyundrive-webdav/discussions/442)帮你 debug 🤪
