### ISSUE TITLE
7/1晚上修复的版本，不能使用指定的用户名挂载，只能留空为匿名

### ISSUE THREAD

**Issue by godt2p4** [messense/aliyundrive-webdav#471]
### 问题描述

7/1晚上修复的版本，不能使用指定的用户名挂载，只能留空为匿名

### 重现步骤

用户名不能设置，只能留空，否则无法正确读取目录，显示无效的用户名

### 版本

1.5.1-1

### 运行平台

openwrt

### refresh token 获取方式

网页版

### 日志

无

**Comment by messense** [comment]
Can not reproduce.
