### ISSUE TITLE
Windows版本二维码无法识别

### ISSUE THREAD

**Issue by F7s** [messense/aliyundrive-webdav#472]
### 问题描述

如题

### 重现步骤

点击Windows的可执行文件，弹出命令提示符，命令提示符会显示一个二维码，可是这个二维码无法进行扫描，屏幕分辨率为1080P，缩放比例为100%

### 版本

aliyundrive-webdav-v1.5.1.x86_64-pc-windows-msvc

### 运行平台

Windows

### refresh token 获取方式

无

### 日志

![image](https://user-images.githubusercontent.com/58980149/176909008-c884a00c-a896-4027-92f1-0998d198230f.png)

**Comment by Gokou-Ruri** [comment]
识别不了是因为垃圾CMD和PS字符间有空格，导致二维码里出现了黑色细线。
换成WT就能识别了。

**Comment by F7s** [comment]
> 

感谢解答

**Comment by Gokou-Ruri** [comment]
> > 
> 
> 感谢解答

或者你也可以用命令行：`aliyundrive-webdav -r`来指定token，token的获取方式在该项目主页就能看到。

**Comment by yburger** [comment]
我这的情况是直接打开在CMD窗口显示的二维码扫描不了，powershell里运行可以识别

**Comment by yuyi4511** [comment]
> 或者你也可以用命令行：`aliyundrive-webdav -r`来指定token，token的获取方式在该项目主页就能看到。

通过上述方式 已经挂挂载到了自己的网盘：
[2m2022-07-09T12:32:59.993477Z[0m [32m INFO[0m [2maliyundrive_webdav[0m[2m:[0m listening on http://0.0.0.0:
请问这个端口如何访问   浏览器里打不开  0000换成本机ip也不行，RaiDrice 没有用户名和密码。。。。

**Comment by yburger** [comment]
> > 或者你也可以用命令行：`aliyundrive-webdav -r`来指定token，token的获取方式在该项目主页就能看到。
> 
> 通过上述方式 已经挂挂载到了自己的网盘： �[2m2022-07-09T12:32:59.993477Z�[0m �[32m INFO�[0m �[2maliyundrive_webdav�[0m�[2m:�[0m listening on http://0.0.0.0:8080 请问这个端口如何访问 浏览器里打不开 0000换成本机ip也不行，RaiDrice 没有用户名和密码。。。。

监听地址可以不用改，保持默认监听0.0.0.0:8080的话本地访问http://127.0.0.1:8080就可以，如果你没有设置webdav访问密码又想在RaiDrive里访问，需要在RaiDrive设置里的账户那一栏后面勾选“匿名”，同时不要忘记把地址那一栏前面的“√”取消掉（关闭https）
