### ISSUE TITLE
文件更新后不会触发同步

### ISSUE THREAD

**Issue by Ligengxin96** [messense/aliyundrive-webdav#473]
### 问题描述

一个日志文件每天都会定时写入内容，但是在文件内容更新后没有触发同步，云端的文件内容还是以前的

### 重现步骤

无

### 版本

messense/aliyundrive-webdav:latest

### 运行平台

Docker

### refresh token 获取方式

网页版

### 日志

无

**Comment by messense** [comment]
不负责同步，看你用的同步软件有没有日志排查下。
