### ISSUE TITLE
当查询文件状态时，请求头不包含Depth:0将返回403

### ISSUE THREAD

**Issue by dangjinghao** [messense/aliyundrive-webdav#476]
### 问题描述

使用`PROPFIND`请求查询某文件状态时，请求头上若不添加“depth: 0”，本程序将返回403 forbidden响应
~~经测试发现cloudreve，alist的webdav不添加depth可正常运行不会返回403响应~~
是否可以对无depth请求头的请求正常返回数据。

### 重现步骤

1. 可使用python3的webdav4库复现

```
from webdav4.client import Client
client = Client(base_url = "http://domain:port",auth=("name","password"))
client.exists("/file")

```
2. curl:`curl -k -i --raw  -X PROPFIND "http://domain:port/file.txt"-H "Content-Type: application/xml" -H "Authorization: Basic xxx" 
`
3. 应该正常的结果curl:`curl -k -i --raw  -X PROPFIND "http://domain:port/file.txt"-H "Content-Type: application/xml" -H "Authorization: Basic xxx" -H "Depth: 0"`

### 版本

1.5.1

### 运行平台

docker

### refresh token 获取方式

网页版

### 日志

无

**Comment by messense** [comment]
需要 API 建议直接访问阿里云盘接口，没必要绕一道 WebDAV.

**Comment by CercisSuoh** [comment]
我在使用 `webdav4` 软件包访问该项目搭建的webdav时, 也遇到了相同情况, 在调用`webdav4.client.exists()` 或者 `webdav4.client.isdir()` 等函数时也会返回403.

发现使用 `webdav4.fsspec` 代替 `webdav4.client` 可以解决大多数此类 403 Forbidden 问题, 不过 `webdav4.fsspec` 不包含`PROPFIND` 请求.

```python
from webdav4.fsspec import WebdavFileSystem
```

希望对你有帮助

参考
https://skshetry.github.io/webdav4/index.html#fsspec
https://filesystem-spec.readthedocs.io/en/latest/#
