### ISSUE TITLE
更新到1.6版本后，无法启动

### ISSUE THREAD

**Issue by byhooi** [messense/aliyundrive-webdav#479]
### 问题描述

2022年07月02日 22:26:09: ERROR[0m [2maliyundrive_webdav[0m[2m:[0m failed to check for update: IoError: no /proc/self/exe available. Is /proc mounted?

### 重现步骤

卸载1.5版本后更新到1.6版本，启动失败

### 版本

1.6

### 运行平台

Koolshare 梅林固件

### refresh token 获取方式

网页版

### 日志

2022年07月02日 22:26:09: ERROR[0m [2maliyundrive_webdav[0m[2m:[0m failed to check for update: IoError: no /proc/self/exe available. Is /proc mounted?

**Comment by messense** [comment]
应该不影响使用，这个报错只是打印了日志。
