### ISSUE TITLE
请问这个报错是什么问题？该如何解决？

### ISSUE THREAD

**Issue by PhioosJ** [messense/aliyundrive-webdav#482]
### 问题描述

前两天用得好好的，今天莫名其妙就打不开插件了，更新到最新版本也没用。

错误原因：
ERROR[0m [2maliyundrive_webdav [0m [2m: [0m failed to check for update: NetworkError: api request failed with status: 401 - for: "https://api.github.com/repos/messense/aliyundrive-webdav/releases/latest"

-----------------------------------------------------------------------------------------------------------
其他信息：
华硕AC86U 梅林386.5

aliyundrive-webdav 版本： [aliyundrivewebdav-merlin-arm384-aarch64.tar.gz] (1.6.0)

### 重现步骤

![微信图片_20220703051450](https://user-images.githubusercontent.com/100673855/177016524-2f98e9ff-bacf-4056-96a7-109ec31e26f6.jpg)

### 版本

1.6.0

### 运行平台

华硕AC86U 梅林386.5

### refresh token 获取方式

网页

### 日志

ERROR[0m [2maliyundrive_webdav [0m [2m: [0m failed to check for update: NetworkError: api request failed with status: 401 - for: "https://api.github.com/repos/messense/aliyundrive-webdav/releases/latest"

**Comment by messense** [comment]
Fixed in v1.6.1.
