### ISSUE TITLE
merlin clash无法启动aliyundrive-webdav

### ISSUE THREAD

**Issue by TsanChao** [messense/aliyundrive-webdav#487]
### 问题描述

2022年07月03日 15:00:38: 当前已进入aliyundrivewebdav_config.sh
2022年07月03日 15:00:38: 当前已进入aliyundrivewebdavconfig.sh执行
2022年07月03日 15:00:38: 先结束进程
2022年07月03日 15:00:38: 参数为：8321 -r xxxxxxxxxxxx --root / -S 10485760 --cache-size 1000
2022年07月03日 15:00:43: aliyundrive 进程启动失败！请检查参数是否存在问题，即将关闭
2022年07月03日 15:00:43: 失败原因：
2022年07月03日 15:00:43: Error: api request failed with status: 401 - for: "https://api.github.com/repos/messense/aliyundrive-webdav/releases/latest"
 

### 重现步骤

启动即出现

### 版本

1.6.2

### 运行平台

路由器

### refresh token 获取方式

网页版

### 日志

2022年07月03日 15:00:38: 当前已进入aliyundrivewebdav_config.sh
2022年07月03日 15:00:38: 当前已进入aliyundrivewebdavconfig.sh执行
2022年07月03日 15:00:38: 先结束进程
2022年07月03日 15:00:38: 参数为：8321 -r xxxxxxxxxxxx --root / -S 10485760 --cache-size 1000
2022年07月03日 15:00:43: aliyundrive 进程启动失败！请检查参数是否存在问题，即将关闭
2022年07月03日 15:00:43: 失败原因：
2022年07月03日 15:00:43: Error: api request failed with status: 401 - for: "https://api.github.com/repos/messense/aliyundrive-webdav/releases/latest"

**Comment by messense** [comment]
检查版本。。。看起来根本不是 1.6.2。

**Comment by TsanChao** [comment]
> 检查版本。。。看起来根本不是 1.6.2。
确实是，下的是aliyundrivewebdav-merlin-arm384-armv7.tar.gz

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/10399848/177029230-264044b8-8c04-4a74-9acc-93d7dd952c18.png">

**Comment by messense** [comment]
1.6.2 不可能打印 Error.

https://github.com/messense/aliyundrive-webdav/commit/6cdbf7c5df77a923e3f2c1bcfc04c82cb03e2051

**Comment by messense** [comment]
你现在显示 1.6.2 可能是中间某次自动更新成功了。。。

**Comment by TsanChao** [comment]
> 1.6.2 不可能打印 Error.
> 
> [6cdbf7c](https://github.com/messense/aliyundrive-webdav/commit/6cdbf7c5df77a923e3f2c1bcfc04c82cb03e2051)

是kool share安装的插件
<img width="739" alt="image" src="https://user-images.githubusercontent.com/10399848/177029373-dc0b0d3d-f296-4c05-b209-18f79ac52627.png">

**Comment by TsanChao** [comment]
> 你现在显示 1.6.2 可能是中间某次自动更新成功了。。。

我是路由器上第一次安装，直接下载1.6.2的binary

**Comment by messense** [comment]
> 2022-07-03T04:48:12.192129Z  WARN aliyundrive_webdav: failed to check for update: NetworkError: api request failed with status: 401 - for: "https://api.github.com/repos/messense/aliyundrive-webdav/releases/latest"

是这个 merlin 的启动脚本 grep `error` 有问题，`NetworkError` 包含了 `error`，但实际上这个日志只是个 warning...

**Comment by TsanChao** [comment]
> 但是这个merlin插件，提示完上述warning，就直接退了。进程调不起来

**Comment by messense** [comment]
等 https://github.com/messense/aliyundrive-webdav/actions/runs/2604275893 这里跑完下载下对应的版本试下吧。

**Comment by TsanChao** [comment]
> 

这个版本可以正常启动了
