### ISSUE TITLE
无法请求github服务器的情况下无法正常启动

### ISSUE THREAD

**Issue by yexun1995** [messense/aliyundrive-webdav#491]
### 问题描述

升级插件为1.6.2版本后尝试启动，提示无法请求Github的版本更新api，所以启动失败。尝试卸载后重新安装，问题依旧。
补充：我这边的宽带无法保证稳定访问github，希望更新功能可以做成选项，或者连接不上更新服务器，可以继续尝试启动。

### 重现步骤

1.确认当前网络无法正常访问 api.github.com
2.获取正确的refresh token，填写到相应区域
3.启动扩展

### 版本

v1.6.2

### 运行平台

梅林 （RT-AX68U）

### refresh token 获取方式

网页版

### 日志

2022年07月03日 21:33:57: 当前已进入aliyundrivewebdav_config.sh
2022年07月03日 21:33:57: 当前已进入aliyundrivewebdavconfig.sh执行
2022年07月03日 21:33:57: 先结束进程
2022年07月03日 21:33:57: 参数为：8080 -r ******************** --root / -S 10485760 --cache-size 1000 --auth-user admin --auth-password admin
2022年07月03日 21:34:02: aliyundrive 进程启动失败！请检查参数是否存在问题，即将关闭
2022年07月03日 21:34:02: 失败原因：
2022年07月03日 21:34:02: Error: api request failed with status: 401 - for: "https://api.github.com/repos/messense/aliyundrive-webdav/releases/latest"

**Comment by texlahoma** [comment]
ax86u更新1.6.2有同样的问题 退回到1.5.1就好了
