### ISSUE TITLE
梅林380固件显示没有找到离线安装包

### ISSUE THREAD

**Issue by master-yun-yun** [messense/aliyundrive-webdav#492]
### 问题描述

路由器是华硕68U
刷的梅林380固件
目前aliyundrive-webdav版本是1.5.1
离线安装1.6.0和1.6.1，1.6.2
3个版本都显示没有找到离线安装包
无法更新

### 重现步骤

1.前两天不能用，离线安装了1.5.1，正常了
2.发现有1.6.0，离线安装1.6.0，提示 没有找到离线安装包！
3.1.6.1版本，离线安装，依旧提示 没有找到离线安装包！
4.1.6.2版本，离线安装，依旧提示 没有找到离线安装包！

### 版本

aliyundrive-webdav版本是1.5.1

### 运行平台

梅林380.70_0-X7.9.1

### refresh token 获取方式

网页版

### 日志

[: aliyundrivewebdav-merlin-arm380-armv7.tar.gz: unknown operand
==========================
【2022年07月03日 21:51:05】: 开启软件离线安装！
【2022年07月03日 21:51:05】: 没有找到离线安装包！
【2022年07月03日 21:51:05】: 删除相关文件并退出...
【2022年07月03日 21:51:06】: ======================== end ============================
 
XU6J03M6

**Comment by messense** [comment]
🤷‍♂️
