### ISSUE TITLE
目录缓存未更新

### ISSUE THREAD

**Issue by eritpchy** [messense/aliyundrive-webdav#5]
操作步骤
1. 用webdav打开当前目录
2. 网页客户端上传文件, 或改名
3. webdav刷新当前目录
4. 可见文件不存在

**Comment by messense** [comment]
[v0.1.16](https://github.com/messense/aliyundrive-webdav/releases/tag/v0.1.16) 版本应该对绝大多数情况目录缓存都是实时更新的了。

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/commit/b32a7617855713b37a9f6765429a87e57f455786 阿里云限制了刷新文件列表 API 的调用频率，revert 了之前的变更，现在在网页端操作需要等缓存过期才能看见了，by design.

**Comment by eritpchy** [comment]
啊 十分不幸

**Comment by JsonSong89** [comment]
可以用刷新动作来触发吗?

**Comment by messense** [comment]
> 可以用刷新动作来触发吗?
> 
> 

不能，无法区分正常列目录还是强制刷新目录。

**Comment by young40** [comment]
貌似可以在需要刷新的目录, 新建一个空文件夹来强制刷新当前目录.
