### ISSUE TITLE
命令行运行的refresh_token会自动更新吗？

### ISSUE THREAD

**Issue by PHCSJC** [messense/aliyundrive-webdav#50]
大佬你好，请问，命令行形式的refresh_token会自动更新吗？谢谢！

**Comment by messense** [comment]
会，可以看日志里面的 refresh_token 记录。

**Comment by PHCSJC** [comment]
那如果token变了，在系统重启后，需要从日志里找到新的token再启动吗？

**Comment by messense** [comment]
是的。

**Comment by PHCSJC** [comment]
感谢，那我还是用docker版本的吧，这个每次启动不用再手动更新token了吧？

**Comment by messense** [comment]
目前都需要，因为没有在内存之外存储刷新后的 refresh_token

**Comment by PHCSJC** [comment]
明白了，另一个大佬做的docker版本可以存储token，用的是映射，大佬能否也考虑下呢？非常感谢！

**Comment by messense** [comment]
Implemented in main branch.

可以增加 `--workdir /path/to/some/directory` 启用 refresh_token 落盘保存。

**Comment by PHCSJC** [comment]
大佬你好，--workdir不是指定命令的运行目录吗？怎么会是refresh_token落盘呢？落盘不应该是--volume参数吗？请大佬指点，谢谢！

**Comment by messense** [comment]
不是 docker 的 --workdir，Dockerfile 里面配置过了，docker 运行的话只需要配置 `-v`/`--volume`，命令行运行配置 `--workdir`

https://github.com/messense/aliyundrive-webdav/blob/7eb7f1efc3f798e7695ac7848bdb06cf5e0a588f/Dockerfile#L15

```bash
docker run -d --name=aliyundrive-webdav --restart=unless-stopped -p 8080:8080 -v /etc/aliyundrive-webdav/:/etc/aliyundrive-webdav/ -e REFRESH_TOKEN='refresh token' messense/aliyundrive-webdav
```

**Comment by PHCSJC** [comment]
> 不是 docker 的 `--workdir`，Dockerfile 里面配置过了，docker 运行的话只需要配置 `-v`/`--volume`，命令行运行配置 `--workdir`
> 
> https://github.com/messense/aliyundrive-webdav/blob/7eb7f1efc3f798e7695ac7848bdb06cf5e0a588f/Dockerfile#L15
> 
> ```shell
> docker run -d --name=aliyundrive-webdav --restart=unless-stopped -p 8080:8080 -v /etc/aliyundrive-webdav/:/etc/aliyundrive-webdav/ -e REFRESH_TOKEN='refresh token' messense/aliyundrive-webdav
> ```
> 
> https://github.com/messense/aliyundrive-webdav#%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%94%A8%E6%B3%95

明白了明白了，非常感谢大佬，已经配置好了，在本地磁盘下的/etc/aliyundrive-webdav/路径下也可以看到token了
