### ISSUE TITLE
群晖 Docker 1.7.1 启动错误 HTTP status client error (405 Method Not Allowed) 

### ISSUE THREAD

**Issue by xtremforce** [messense/aliyundrive-webdav#501]
### 问题描述

镜像已经更新到 1.7.1
重新获取了 Token
问题依旧，无法启动容器。

### 重现步骤

群晖删除并重新下载了容器

### 版本

1.7.1

### 运行平台

群晖 Docker

### refresh token 获取方式

网页版

### 日志

ERROR aliyundrive_webdav::drive: refresh token failed: HTTP status client error (405 Method Not Allowed) for url (https://www.aliyundrive.com/): Method POST not allowed

Error: initialize aliyundrive client failed

**Comment by messense** [comment]
你可能是 Docker image 本地缓存的受害者。

```bash
docker run --rm messense/aliyundrive-webdav:latest aliyundrive-webdav --version
aliyundrive-webdav 1.7.1
```
