### ISSUE TITLE
在docker中运行不起来，提示post方法不被允许

### ISSUE THREAD

**Issue by vic-miao** [messense/aliyundrive-webdav#506]
### 问题描述

在群辉docker拉取镜像，启动时报错，查看日志，内容是2022-07-07T13:39:47.077460Z ERROR aliyundrive_webdav::drive: refresh token failed: HTTP status client error (405 Method Not Allowed) for url (https://www.aliyundrive.com/): Method POST not allowed

### 重现步骤

1.群晖拉取镜像，是最新版
启动报错，报错内容是2022-07-07T13:39:47.077460Z ERROR aliyundrive_webdav::drive: refresh token failed: HTTP status client error (405 Method Not Allowed) for url (https://www.aliyundrive.com/): Method POST not allowed

### 版本

messense/aliyundrive-webdav:latest

### 运行平台

群晖docker

### refresh token 获取方式

在pc网页的控制台中

### 日志

2022-07-07T13:39:47.077460Z ERROR aliyundrive_webdav::drive: refresh token failed: HTTP status client error (405 Method Not Allowed) for url (https://www.aliyundrive.com/): Method POST not allowed
2022-07-07T13:39:47 Error: initialize aliyundrive client failed

**Comment by DeeDive** [comment]
@messense 您好！感谢您的工作，非常方便！我最近同样遇到这个问题，请问是出了什么fix修复所以关闭了问题吗？我好像没有找到最新的镜像
