### ISSUE TITLE
上传文件出错

### ISSUE THREAD

**Issue by vic-miao** [messense/aliyundrive-webdav#508]
### 问题描述

在docker中上传文件报错
error=request or response body error: error reading a body from connection: connection reset

### 重现步骤

在docker中上传文件报错
error=request or response body error: error reading a body from connection: connection reset

### 版本

1.7.1

### 运行平台

docker

### refresh token 获取方式

在pc网页的控制台中

### 日志

error=request or response body error: error reading a body from connection: connection reset

**Comment by messense** [comment]
网络问题自行排查。
