### ISSUE TITLE
梅林3.0.0.4.386_EA6700_R5.1.5 386版本1.7.1没有一个能装

### ISSUE THREAD

**Issue by clj83318** [messense/aliyundrive-webdav#509]
### 问题描述

把380和384所有版本的预编译包都试过了，都不行显示如下，救救孩子

### 重现步骤

【2022年07月09日 20:16:48】: ====================== step 1 ===========================
【2022年07月09日 20:16:48】: 开启软件离线安装！
【2022年07月09日 20:16:48】: /tmp目录下检测到上传的离线安装包aliyundrivewebdav-merlin-arm384-armv7.tar.gz，大小：3.1M
【2022年07月09日 20:16:48】: 尝试解压离线安装包离线安装包
【2022年07月09日 20:16:48】: 解压完成！
【2022年07月09日 20:16:48】: 准备安装aliyundrivewebdav插件！
【2022年07月09日 20:16:48】: 找到安装脚本！
【2022年07月09日 20:16:48】: 运行安装脚本...
【2022年07月09日 20:16:48】: ====================== step 2 ===========================
/tmp/aliyundrivewebdav/install.sh: source: line 2: can't open '/koolshare/scripts/base.sh'
【2022年07月09日 20:16:49】: 因为aliyundrivewebdav插件安装失败！退出离线安装！
【2022年07月09日 20:16:49】: ======================== end ============================
 
XU6J03M6

### 版本

3.0.0.4.386_EA6700_R5.1.5 386

### 运行平台

3.0.0.4.386_EA6700_R5.1.5 386 梅林

### refresh token 获取方式

网页

### 日志

【2022年07月09日 20:16:48】: ====================== step 1 ===========================
【2022年07月09日 20:16:48】: 开启软件离线安装！
【2022年07月09日 20:16:48】: /tmp目录下检测到上传的离线安装包aliyundrivewebdav-merlin-arm384-armv7.tar.gz，大小：3.1M
【2022年07月09日 20:16:48】: 尝试解压离线安装包离线安装包
【2022年07月09日 20:16:48】: 解压完成！
【2022年07月09日 20:16:48】: 准备安装aliyundrivewebdav插件！
【2022年07月09日 20:16:48】: 找到安装脚本！
【2022年07月09日 20:16:48】: 运行安装脚本...
【2022年07月09日 20:16:48】: ====================== step 2 ===========================
/tmp/aliyundrivewebdav/install.sh: source: line 2: can't open '/koolshare/scripts/base.sh'
【2022年07月09日 20:16:49】: 因为aliyundrivewebdav插件安装失败！退出离线安装！
【2022年07月09日 20:16:49】: ======================== end ============================
 
XU6J03M6

**Comment by master-yun-yun** [comment]
看我的反馈。你把下载下来的安装包文件名改短，比如改为   1.71.tar.tz，然后再离线上传安装。

**Comment by clj83318** [comment]
> 看我的反馈。你把下载下来的安装包文件名改短，比如改为 1.71.tar.gz，然后再离线上传安装。

【2022年07月09日 20:34:56】: ====================== step 1 ===========================
【2022年07月09日 20:34:56】: 开启插件离线安装！
【2022年07月09日 20:34:56】: /tmp目录下检测到上传的离线安装包1.7.1.tar.gz，大小：3.1M
【2022年07月09日 20:34:56】: 当前jffs分区剩余：21708KB, 空间满足，继续安装！
【2022年07月09日 20:34:56】: 尝试解压离线安装包离线安装包
【2022年07月09日 20:34:56】: 解压完成！
【2022年07月09日 20:34:56】: 准备安装aliyundrivewebdav插件！
【2022年07月09日 20:34:56】: 找到安装脚本！
【2022年07月09日 20:34:57】: 运行安装脚本...
【2022年07月09日 20:34:57】: ====================== step 2 ===========================
/tmp/aliyundrivewebdav/install.sh: source: line 2: can't open '/koolshare/scripts/base.sh'
【2022年07月09日 20:34:58】: 因为aliyundrivewebdav插件安装失败！退出离线安装！
【2022年07月09日 20:34:58】: ======================== end ============================

**Comment by clj83318** [comment]
> 看我的反馈。你把下载下来的安装包文件名改短，比如改为 1.71.tar.gz，然后再离线上传安装。

还是不行，大大求解

**Comment by clj83318** [comment]
> 看我的反馈。你把下载下来的安装包文件名改短，比如改为 1.71.tar.gz，然后再离线上传安装。

改成1.tar.gz 也不行

**Comment by master-yun-yun** [comment]
> 

看来不是一个问题。我的是提示没有找到离线安装包，改短了就好了。你这个提示是脚本第几行有问题，和我不一样。

**Comment by messense** [comment]
不支持非 koolshare 梅林固件。
