### ISSUE TITLE
能不能出个Android版

### ISSUE THREAD

**Issue by wekingchen** [messense/aliyundrive-webdav#51]
可以在手机上运行了，直接用nplayer挂载看片

**Comment by messense** [comment]
Android 那就直接用官方客户端呀，为什么要绕道 webdav...

**Comment by wekingchen** [comment]
因为官方客户端播放体验没有专门的播放器好呀，有了webdav可以有更多的选择~

**Comment by Triwind** [comment]
> 因为官方客户端播放体验没有专门的播放器好呀，有了webdav可以有更多的选择~

https://github.com/eritpchy/webdav-aliyundriver-android
