### ISSUE TITLE
群晖docker报错、无法挂载

### ISSUE THREAD

**Issue by hululu1068** [messense/aliyundrive-webdav#511]
### 问题描述

群晖docker一直提示`token`无法验证，`https://websv.aliyundrive.com/token/refresh`解析不到

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/68652362/178660650-5a4902d1-e781-4f82-a96a-e77aaf8810d9.png">

### 重现步骤

docker cli

### 版本

messense/aliyundrive-webdav:latest

### 运行平台

X86_64 DS918+

### refresh token 获取方式

网页、chrome-103.0.5060.114

### 日志

refresh token failed, will wait and retry [3merror[0m[2m=[0merror sending request for url (https://websv.aliyundrive.com/token/refresh): error trying to connect: dns error: failed to lookup address information: Name does not resolve

**Comment by messense** [comment]
自行搜索 issues.

**Comment by wjs876046992** [comment]
@messense 我也遇到这个问题，issues里没找到类似问题，搜什么关键字？

@hululu1068 你解决了吗？
