### ISSUE TITLE
400 bad request 还未完全解决

### ISSUE THREAD

**Issue by geekhuashan** [messense/aliyundrive-webdav#514]
### 问题描述

#276 ，之前报告过问题，后来作者大大更新了版本，使得我**偶尔**上传稍大文件的时候能够成功了，之前完全不行，超过20M的文件没有成功过。

现在还是经常会碰到无法上传文件的情况，我用的是rclone 上传的。查看日志发现400 bad request

### 重现步骤

1. 重置阿里云服务器
2. 安装docker
3. 安装各种软件 aria2 rclone aliyundrive-webdav
4. 下载视频，rclone 上传到阿里云盘
5. 查看日志，报错 400 bad request

### 版本

1.7.4

### 运行平台

linux

### refresh token 获取方式

网页版

### 日志

[400 BAD REQUEST](https://user-images.githubusercontent.com/47098938/178927107-6b23f126-cc0b-4383-bcf0-76a906640622.png)

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/issues/276#issuecomment-1184105105

**Comment by messense** [comment]
Closing per https://github.com/messense/aliyundrive-webdav/issues/276#issuecomment-1184115489
