### ISSUE TITLE
群晖docker配合cloudsync运行时，经常出现莫名文件校验错误导致上传失败，重复上传

### ISSUE THREAD

**Issue by huamike** [messense/aliyundrive-webdav#518]
### 问题描述

cloudsync设定模式为，仅上传本地修改，加密模式。
使用目的是需要备份大量高清资源，然后24小时开机不间断运行了2周以上，感觉不对头（按照系统显示的上传速度，早就该完成了），结果今天查询cloudsync的日志，统计了一下24小时内已经传输完成的任务，发现实际完成的传输量只有实际上传速度推算完成量的10%左右。

进一步再查看dock的运行日志，发现日志中有大量的文件传输错误提示，大概意思好像是文件校验错误。（当时因为搞不清楚问题，结果手快把该映像删除了，没有保留日志，实在抱歉）。

因此推测造成上传进度不理想的原因，应该是上传失败率较高导致的。

### 重现步骤

1.群晖dock上安装并配置映像
2.配置cloudsync，仅上传本地修改，并选择加密，并行上传任务数设定是3
3.上传较大文件（单文件最好不小于4GB，这样应该有较大概率可以发现）

我试了两次都有这种问题，后来尝试其他家做对比，没有继续试。

### 版本

1.7.4

### 运行平台

平台为群晖7.01.42218，相关dock和cloudsync套件为最新版，

### refresh token 获取方式

网页版

### 日志

手快给删了，也背不出来，抱歉。

**Comment by messense** [comment]
没日志的话没办法判断。
