### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by boshi116** [messense/aliyundrive-webdav#520]
### 问题描述

编译出错

### 重现步骤

编译出错

### 版本

1.7.4

### 运行平台

openwrt

### refresh token 获取方式

网页

### 日志

make[3]: Entering directory '/home/ttt/lede/feeds/packages/multimedia/aliyundrive-webdav'
mkdir -p /home/ttt/lede/dl
SHELL= flock /home/ttt/lede/tmp/.aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz.sha256.flock -c '  	/home/ttt/lede/scripts/download.pl "/home/ttt/lede/dl" "aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz.sha256" "skip" "" "https://github.com/messense/aliyundrive-webdav/releases/download/v1.7.1/"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://github.com/messense/aliyundrive-webdav/releases/download/v1.7.1/aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   125  100   125    0     0     49      0  0:00:02  0:00:02 --:--:--   169
mkdir -p /home/ttt/lede/dl
SHELL= flock /home/ttt/lede/tmp/.aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz.flock -c '  /home/ttt/lede/scripts/download.pl "/home/ttt/lede/dl" "aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz" "skip" "" "https://github.com/messense/aliyundrive-webdav/releases/download/v1.7.1/"    '
touch /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.prepared_0a09f835a516fa96b8704f439c06fe4a_6664517399ebbbc92a37c5bb081b5c53_check
mv /home/ttt/lede/dl/aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz.sha256 .
cp /home/ttt/lede/dl/aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz .
shasum -a 256 -c aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz.sha256
aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz: OK
rm aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz.sha256 aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz
tar -C /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/ -zxf /home/ttt/lede/dl/aliyundrive-webdav-v1.7.1.x86_64-unknown-linux-musl.tar.gz
touch /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.prepared_0a09f835a516fa96b8704f439c06fe4a_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.configured_*
rm -f /home/ttt/lede/staging_dir/target-x86_64_musl/stamp/.aliyundrive-webdav_installed
(cd /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/./; if [ -x ./configure ]; then find /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/ -name config.guess | xargs -r chmod u+w; find /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/ -name config.guess | xargs -r -n1 cp --remove-destination /home/ttt/lede/scripts/config.guess; find /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/ -name config.sub | xargs -r chmod u+w; find /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/ -name config.sub | xargs -r -n1 cp --remove-destination /home/ttt/lede/scripts/config.sub; AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1=aliyundrive-webdav-1.7.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1=aliyundrive-webdav-1.7.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1=aliyundrive-webdav-1.7.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/ttt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/ttt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/ttt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include " LDFLAGS="-L/home/ttt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/ttt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro "   ./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.built
touch /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.built_check
echo "aliyundrive-webdav using precompiled binary."
aliyundrive-webdav using precompiled binary.
touch /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.built
rm -rf /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav.installed /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav
mkdir -p /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav
install -d -m0755 /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav/usr/bin
install -m0755 /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/aliyundrive-webdav /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav/usr/bin/aliyundrive-webdav
install -d -m0755 /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav/etc/init.d
install -m0755 ./files/aliyundrive-webdav.init /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav/etc/init.d/aliyundrive-webdav
install: cannot stat './files/aliyundrive-webdav.init': No such file or directory
make[3]: *** [Makefile:81: /home/ttt/lede/build_dir/target-x86_64_musl/aliyundrive-webdav-1.7.1/.pkgdir/aliyundrive-webdav.installed] Error 1
make[3]: Leaving directory '/home/ttt/lede/feeds/packages/multimedia/aliyundrive-webdav'
time: package/feeds/packages/aliyundrive-webdav/compile#0.20#0.14#2.83
    ERROR: package/feeds/packages/aliyundrive-webdav failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/aliyundrive-webdav/compile] Error 1
make[2]: Leaving directory '/home/ttt/lede'
make[1]: *** [package/Makefile:110: /home/ttt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ttt/lede'
make: *** [/home/ttt/lede/include/toplevel.mk:230：world] 错误 2

**Comment by messense** [comment]
参考 CI 配置自行排查。
