### ISSUE TITLE
docker最新的版本还是上传不了文件

### ISSUE THREAD

**Issue by PHCSJC** [messense/aliyundrive-webdav#53]
看到更新说支持上传了，看docker也更新了，就更新了下docker，试了下还是不能上传，请问大佬需要什么信息来调试呢？
docker镜像id是：cb969dcc5b23
webdav是：RaiDrive

**Comment by messense** [comment]
没用过 RaiDrive，贴一下 docker 容器的日志吧，注意脱敏 refresh token.

**Comment by PHCSJC** [comment]
> 没用过 RaiDrive，贴一下 docker 容器的日志吧，注意脱敏 refresh token.

Sep 27 08:46:43.444  INFO aliyundrive_webdav::drive: refresh token succeed refresh_token=**** nick_name=iqVa8z
Sep 27 08:46:43.445  INFO aliyundrive_webdav::drive: found default drive drive_id=8466882
Sep 27 08:46:43.446  INFO aliyundrive_webdav: listening on 0.0.0.0:8080
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31

**Comment by messense** [comment]
这个上传的文件大小是？

**Comment by PHCSJC** [comment]
就一个txt文件，只有几k

**Comment by messense** [comment]
看起来是没有获取到上传地址，得具体看下原因。

**Comment by raydoom** [comment]
Sep 27 09:10:12.273  INFO aliyundrive_webdav: listening on 0.0.0.0:8080
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
Sep 27 09:11:18.687 ERROR aliyundrive_webdav::vfs: refresh directory file list failed error=HTTP status client error (429 Too Many Requests) for url (https://api.aliyundrive.com/adrive/v3/file/list)
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
[root@centos7-16 ~]# docker logs 9d2
Sep 27 09:10:12.266  INFO aliyundrive_webdav::drive: refresh token succeed refresh_token=1b17de40b94244a09ac1f5e86c9665fc nick_name=maxd
Sep 27 09:10:12.270  INFO aliyundrive_webdav::drive: found default drive drive_id=1196115
Sep 27 09:10:12.273  INFO aliyundrive_webdav: listening on 0.0.0.0:8080
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
Sep 27 09:11:18.687 ERROR aliyundrive_webdav::vfs: refresh directory file list failed error=HTTP status client error (429 Too Many Requests) for url (https://api.aliyundrive.com/adrive/v3/file/list)
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31

**Comment by raydoom** [comment]
Sep 27 09:10:12.273  INFO aliyundrive_webdav: listening on 0.0.0.0:8080
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
Sep 27 09:11:18.687 ERROR aliyundrive_webdav::vfs: refresh directory file list failed error=HTTP status client error (429 Too Many Requests) for url (https://api.aliyundrive.com/adrive/v3/file/list)
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/vfs.rs:438:31

**Comment by messense** [comment]
@raydoom 你这个也是 RaiDrive 吗？

**Comment by messense** [comment]
Blocked by https://github.com/miquels/webdav-handler-rs/issues/17

**Comment by messense** [comment]
RaiDrive 不兼容，我试了 macOS 下 ForkLift 是好的。

**Comment by raydoom** [comment]
> @raydoom 你这个也是 RaiDrive 吗？

对，是RaiDrive ，应该是不兼容，我试了winscp，也是没问题

**Comment by messense** [comment]
可以试下 0.4.0：https://github.com/messense/aliyundrive-webdav/releases/tag/v0.4.0

**Comment by jadkg** [comment]
我上传没有问题了

**Comment by messense** [comment]
还有问题的话，可以贴下日志 reopen 这个 issue 或者建新的 issue.

**Comment by PHCSJC** [comment]
大佬又来麻烦你了，我在debian 10上直接挂载，然后往里复制文件，非常不稳定，没有报错却实际没有成功，或者报目录不存在。
挂载命令：
mount -t davfs http://127.0.0.1:8080 /mnt
复制命令：
就是简单的cp几个文件或目录，文件也不大，不超过50M。

**Comment by messense** [comment]
@PHCSJC 可以试一下 0.4.2，修正了创建文件夹之后缓存没有更新的问题，可能和你的问题相关。

**Comment by qinyuhang** [comment]
Hello 我使用Docker版本，macOS原生Finder挂载后，无法上传文件。返回错误-36.

https://user-images.githubusercontent.com/6239057/137106480-b2d20097-0e29-4be3-86a7-0e796b2ed195.mov


报错为 
```
Oct 13 09:34:09.877 ERROR aliyundrive_webdav::vfs: delete file before upload failed file_name=SuspiciousPackage.dmg error=HTTP status client error (429 Too Many Requests) for url (https://api.aliyundrive.com/v2/recyclebin/trash)
```

**Comment by messense** [comment]
@qinyuhang 不建议用 macOS Finder 挂载，Finder 的行为比较怪异，会发很多 `._` 开头的文件名请求，导致请求量过多被 ratelimt.

可以用 forklift 等支持 WebDAV 的软件。
