### ISSUE TITLE
rclone 映射到本地磁盘后 文件拖入文件夹或用Ctrl+X，Ctrl+V在文件夹之间移动时出错

### ISSUE THREAD

**Issue by simonnet126** [messense/aliyundrive-webdav#536]
### 问题描述

aliyundrive-webdav --host 127.0.0.1 --port 8282 --auth-user simon  --auth-password xxx --refresh-token xxx

rclone 使用如下参数映射  rclone mount ALIYUNPAN:/  H: --no-update-modtime --cache-dir G:\RcloneCache --vfs-cache-mode full

[ALIYUNPAN]
type = webdav
url = http://127.0.0.1:8282
vendor = nextcloud
user = simon
pass = xxx

运行后能正常访问，读写文件，但将磁盘中的文件拖入文件夹时出错。错误0x8007045D：由于I/O 设备错误，无法运行此项请求。
（如果出现在文件夹中的文件重复需要覆盖时出现的概率非常高，几乎每次都出错）

![image](https://user-images.githubusercontent.com/48544966/181890396-7a8e8749-85ae-41e9-9e28-22e5a9537671.png)
![image](https://user-images.githubusercontent.com/48544966/181890470-4f6e5a9b-435b-445f-867b-42682e047106.png)

不知道是不是rclone的问题，还是aliyundrive-webdav的原因，谢谢！

### 重现步骤

1.rclone映射为本地磁盘
2.新建一个文件夹
3.新建一个文本文件，拖入文件夹（可能会出错）
4.再新建一个文本文件，拖入文件夹（提示覆盖，基本就会出错）

### 版本

1.8.9

### 运行平台

windows 10

### refresh token 获取方式

windows

### 日志

在阿里云盘里文件已放入回收站，怀疑是不是先做了删除源文件处理，再做添加文件，导致找不到源导致。

**Comment by messense** [comment]
请提供日志。

**Comment by simonnet126** [comment]
![image](https://user-images.githubusercontent.com/48544966/181908146-5be042c0-1a21-498f-be9d-ab50424301bc.png)

[2m2022-07-30T11:06:04.460257Z[0m [34mDEBUG[0m [2maliyundrive_webdav::drive[0m[2m:[0m list file [3mdrive_id[0m[2m=[0m1000175 [3mparent_file_id[0m[2m=[0m62e50f2a3fa51a254dc8459d98ad12980eb8ef75 [3mmarker[0m[2m=[0mNone
[2m2022-07-30T11:06:04.594823Z[0m [34mDEBUG[0m [2mreqwest::async_impl::client[0m[2m:[0m response '200 OK' for https://api.aliyundrive.com/v2/file/list
[2m2022-07-30T11:06:04.600146Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: insert [3mkey[0m[2m=[0m/资料备份/新建文件夹
[2m2022-07-30T11:06:04.600646Z[0m [34mDEBUG[0m [2maliyundrive_webdav::vfs[0m[2m:[0m read_dir cache miss [3mpath[0m[2m=[0m/资料备份/新建文件夹
[2m2022-07-30T11:06:04.603538Z[0m [34mDEBUG[0m [2maliyundrive_webdav::vfs[0m[2m:[0m fs: metadata [3mpath[0m[2m=[0m/资料备份/新建文件夹
[2m2022-07-30T11:06:04.604565Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: get [3mkey[0m[2m=[0m/资料备份
[2m2022-07-30T11:06:04.605511Z[0m [34mDEBUG[0m [2maliyundrive_webdav::vfs[0m[2m:[0m fs: create_dir [3mpath[0m[2m=[0m/资料备份/新建文件夹
[2m2022-07-30T11:06:04.606135Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: get [3mkey[0m[2m=[0m/
[2m2022-07-30T11:06:04.607067Z[0m [34mDEBUG[0m [2maliyundrive_webdav::drive[0m[2m:[0m create folder [3mparent_file_id[0m[2m=[0m62dc04a242ebf5ec4d924fd3822a8a0d295ceaa3 [3mname[0m[2m=[0m新建文件夹
[2m2022-07-30T11:06:04.711204Z[0m [34mDEBUG[0m [2mreqwest::async_impl::client[0m[2m:[0m response '201 Created' for https://api.aliyundrive.com/v2/file/create
[2m2022-07-30T11:06:04.712262Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: invalidate [3mpath[0m[2m=[0m/资料备份 [3mkey[0m[2m=[0m/资料备份
[2m2022-07-30T11:06:04.715802Z[0m [34mDEBUG[0m [2maliyundrive_webdav::vfs[0m[2m:[0m fs: metadata [3mpath[0m[2m=[0m/资料备份/新建文本文档.txt
[2m2022-07-30T11:06:04.718891Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: get [3mkey[0m[2m=[0m/资料备份
[2m2022-07-30T11:06:04.719522Z[0m [34mDEBUG[0m [2maliyundrive_webdav::drive[0m[2m:[0m get file by path [3mdrive_id[0m[2m=[0m1000175 [3mpath[0m[2m=[0m/资料备份/新建文本文档.txt
[2m2022-07-30T11:06:04.800319Z[0m [34mDEBUG[0m [2mreqwest::async_impl::client[0m[2m:[0m response '404 Not Found' for https://api.aliyundrive.com/v2/file/get_by_path
[2m2022-07-30T11:06:04.800707Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: get [3mkey[0m[2m=[0m/
[2m2022-07-30T11:06:04.802810Z[0m [34mDEBUG[0m [2maliyundrive_webdav::vfs[0m[2m:[0m read_dir cache hit [3mpath[0m[2m=[0m/
[2m2022-07-30T11:06:04.807439Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: get [3mkey[0m[2m=[0m/
[2m2022-07-30T11:06:04.808441Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: get [3mkey[0m[2m=[0m/资料备份
[2m2022-07-30T11:06:04.809289Z[0m [34mDEBUG[0m [2maliyundrive_webdav::drive[0m[2m:[0m list file [3mdrive_id[0m[2m=[0m1000175 [3mparent_file_id[0m[2m=[0m62dc04a242ebf5ec4d924fd3822a8a0d295ceaa3 [3mmarker[0m[2m=[0mNone
[2m2022-07-30T11:06:05.005926Z[0m [34mDEBUG[0m [2mreqwest::async_impl::client[0m[2m:[0m response '200 OK' for https://api.aliyundrive.com/v2/file/list
[2m2022-07-30T11:06:05.006360Z[0m [34mDEBUG[0m [2maliyundrive_webdav::cache[0m[2m:[0m cache: insert [3mkey[0m[2m=[0m/资料备份
[2m2022-07-30T11:06:05.014262Z[0m [34mDEBUG[0m [2maliyundrive_webdav::vfs[0m[2m:[0m read_dir cache miss [3mpath[0m[2m=[0m/资料备份
