### ISSUE TITLE
1.10 docker 版本获取文件报错

### ISSUE THREAD

**Issue by irockstar** [messense/aliyundrive-webdav#561]
### 问题描述

更新 messense/aliyundrive-webdav:latest （1.10）镜像后 WebDAV 可以展示列表，但无法下载文件，更新浏览器token也无效，报错信息如图

![WX20220816-131647](https://user-images.githubusercontent.com/1676743/184803828-bd58bcf2-182e-4dac-b041-372fc56ccf24.png)

修改为 1.9 版本镜像可以正常使用

### 重现步骤

1. 启动 docker 服务
2. 浏览器访问 web:8080
3. 列表可以展示，文件详情报 xml 错误
4. 更换为1.9版本镜像后正常使用

### 版本

1.10

### 运行平台

Docker

### refresh token 获取方式

网页版

### 日志

![WX20220816-131529](https://user-images.githubusercontent.com/1676743/184804474-f6fd54c8-d285-49f3-b6c9-2bbf82cf4f5f.png)

**Comment by messense** [comment]
可以试一下 `messense/aliyundrive-webdav:main`

**Comment by WHYBBE** [comment]
为什么docker用latest标签获取到的是一个很早之前的版本
在pull下来之后，用`docker image inspect xxx`可以看到版本是1.1.0，2021-12-23发布的
有点奇怪

**Comment by irockstar** [comment]
是不是使用了 阿里云 的 docker 加速？ 以前我遇到过阿里云镜像版本不同步的情况 @WHYBBE

**Comment by WHYBBE** [comment]
> 是不是使用了 阿里云 的 docker 加速？ 以前我遇到过阿里云镜像版本不同步的情况 @WHYBBE

还真是，把镜像一关latest的版本就对了，看来以后用镜像的时候得注意一下了，我以前都无条件信任的，不过昨天我用哈希标签勉强解决了
