### ISSUE TITLE
thread 'tokio-runtime-worker' panicked

### ISSUE THREAD

**Issue by Ah-Bo** [messense/aliyundrive-webdav#58]
![图片](https://user-images.githubusercontent.com/35646849/135737355-a37031ac-ea52-4611-85ff-7a7a4338d911.png)

**Comment by Ah-Bo** [comment]
可以正常使用

**Comment by messense** [comment]
最新版本？

**Comment by Ah-Bo** [comment]
应该是的
![图片](https://user-images.githubusercontent.com/35646849/135789066-9e3c6b4e-ba10-4d6a-9e26-a3a0eb9da7e7.png)
