### ISSUE TITLE
aliyundrive_webdav::drive: refresh token faile d: Request error: error sending request for url (https: //auth.aliyundrive.com/v2/account/token): error trying to connect: dns error: failed to lookup address in formation: Try again Error: get default drive id failed

### ISSUE THREAD

**Issue by LucifielHack** [messense/aliyundrive-webdav#634]
### 问题描述

提示这个，是该版本已经失效了吗？

### 重现步骤

正常安装提示该内容

### 版本

latest

### 运行平台

NAS docker

### refresh token 获取方式

网页版

### 日志

aliyundrive_webdav::drive: refresh token faile
d: Request error: error sending request for url (https: //auth.aliyundrive.com/v2/account/token): error trying to connect: dns error: failed to lookup address in formation: Try again
Error: get default drive id failed

**Comment by messense** [comment]
网络问题自行排查。

**Comment by zptqghsw** [comment]
> 

感觉不是网络问题，我也遇到此问题，域名可以在容器里面ping通，但是日志一直报这个错

**Comment by Lonor** [comment]
same here. 
websv.aliyundrive.com 
This FQDN seems already invalid.

```
nslookup websv.aliyundrive.com
Server:		114.114.114.114
Address:	114.114.114.114#53

** server can't find websv.aliyundrive.com: NXDOMAIN
```
