### ISSUE TITLE
Merlin arm 384 无法启动

### ISSUE THREAD

**Issue by laiqidong** [messense/aliyundrive-webdav#663]
### 问题描述

无法启动

### 重现步骤

输入token，点击提交

### 版本

1.10.3

### 运行平台

AC88U

### refresh token 获取方式

网页版

### 日志

admin@RT-AC88U-7918:/jffs/.koolshare/scripts# /koolshare/bin/aliyundrive-webdav -I --no-self-upgrade --workdir /var/run/aliyundrivewebdav --host 0.0.0.0 -p 8080 -r ce7e68752ccd4863b89e4e174d08e32a --r
oot / -S 10485760 --cache-size 1000 

/koolshare/bin/aliyundrive-webdav: line 6: syntax error: unexpected "&"

**Comment by messense** [comment]
没有梅林设备了。
