### ISSUE TITLE
x86/x64版本的二维码有问题

### ISSUE THREAD

**Issue by simonchen** [messense/aliyundrive-webdav#664]
### 问题描述

![image](https://user-images.githubusercontent.com/345840/203362547-1165a9c0-65e6-4118-af58-bc4d6ca0c67f.png)
生成的二维码明显不正常，用阿里云app无法扫码

### 重现步骤

aliyundrive-webdav.exe qr login

### 版本

1.10.3

### 运行平台

Windows

### refresh token 获取方式

命令行获取: aliyundrive-webdav qr login

### 日志

直接看错误的二维码图

**Comment by messense** [comment]
用 Windows Terminal。

**Comment by simonchen** [comment]
> 

是在cmd.exe / powershell.exe 中执行的，windows 11系统
