### ISSUE TITLE
华硕AC86u 梅林固件，阿里云盘WebDAV 1.10.2 , 路由器重启后，软件中心的阿里云盘WebDAV 没自动重启

### ISSUE THREAD

**Issue by jesustoachild** [messense/aliyundrive-webdav#665]
### 问题描述

华硕AC86u 梅林固件，阿里云盘WebDAV 1.10.2 , 路由器重启后，软件中心的阿里云盘WebDAV 没自动重启
求帮助

### 重现步骤

1. 软件中心，手动开启没问题
2. 系统重启后，还需要手动重启 WebDAV

### 版本

1.10.2

### 运行平台

AC86u 梅林

### refresh token 获取方式

网页

### 日志

哪里找？

**Comment by messense** [comment]
不用梅林了。
