### ISSUE TITLE
挂载vhdx虚拟磁盘报错

### ISSUE THREAD

**Issue by gaoweihe** [messense/aliyundrive-webdav#666]
### 问题描述

希望可以支持Windows中vhdx文件挂载。
目的是，将虚拟磁盘（VHD）存在阿里云盘中。将阿里云盘挂载到本地，再将阿里云盘中的VHD文件挂载到Windows文件系统中。该操作主要用于在阿里云盘中存储虚拟机/虚拟磁盘文件。

### 重现步骤

在Windows磁盘管理附加阿里云盘中的VHD，提示参数错误。
![image](https://user-images.githubusercontent.com/39734584/204092931-d8787dbc-2939-4c40-9873-8aadda25886d.png)

在Windows资源管理器中双击直接打开阿里云盘中的`.vhdx`文件，提示无法装载文件。
![image](https://user-images.githubusercontent.com/39734584/204093006-f2fb8a89-bb6e-4d68-9d49-95b466a5dfae.png)

### 版本

v1.10.3

### 运行平台

Windows 11 

### refresh token 获取方式

App

### 日志

程序本身无报错。Windows磁盘管理报错。

**Comment by messense** [comment]
Nope.
