### ISSUE TITLE
Swift backup无法覆盖旧文件，提示网络500 Internet server error

### ISSUE THREAD

**Issue by kissunyeason** [messense/aliyundrive-webdav#673]
### 问题描述

部分文件无法上传覆盖旧数据，手机app提示500错误

### 重现步骤

1.使用Swift back 备份手机数据
2.初次备份提示成功且无错误
3.再次备份部分app，覆盖旧数据时提示错误，500错误
4.使用手机其他app 复制文件正常
5.使用其他阿里云其他webdav挂载，再用Swift back软件备份不存在这样的错误

### 版本

1.10.3

### 运行平台

红米AX6 openwrt

### refresh token 获取方式

App

### 日志

![Screenshot_20221217-084037_Swift_Backup](https://user-images.githubusercontent.com/17369666/208213942-0253f1b7-fb62-474c-8601-dfaac0dbaaed.png)
![Screenshot_20221217-084302_Swift_Backup](https://user-images.githubusercontent.com/17369666/208213951-2d3a80b2-42a7-4336-8940-b9500d6de7b2.png)

Swift backup日志
[DeviceInfo start]
Build: Xiaomi/evolution_cmi/cmi:13/TD1A.221105.001/yarpiin11292301:userdebug/release-keys
Model: Xiaomi/Mi 10 Pro
OS: 13, SDK 33
Secondary user: false (id=0)
Locale: zh_CN
Root state: 25.2:MAGISK:R (25200)
App info: Running org.swiftapps.swiftbackup v4.2.3 (561)
Folder: /storage/emulated/0/SwiftBackup/accounts/2e687cef5019709d/
User account:
[DeviceInfo end]

[SwiftLogger start]
17/12/22 08:42:30.130/AppListActivity: Opened
17/12/22 08:42:32.800/DetailActivity: Opened
17/12/22 08:42:32.833/DetailActivity: Opened app details for 阿里云盘 (com.alicloud.databox)
17/12/22 08:42:35.561/TaskService: Started
17/12/22 08:42:35.579/TaskActivity: Opened
17/12/22 08:42:35.662/TaskManager: Executing AppsTask: params=Backup(isArchivedBackup=false) totalItems=1
17/12/22 08:42:35.664/AppBackupManager: Processing 1/1
17/12/22 08:42:35.816/SsaidHelper: Built with 49 valid entries
17/12/22 08:42:35.860/NotificationAccessMap: Map built with 2 entries
17/12/22 08:42:35.939/AccessibilityServicesMap: Map built with 1 entries
17/12/22 08:42:36.065/AppBackupTask: Started backup: 阿里云盘 (com.alicloud.databox)
17/12/22 08:42:36.066/AppBackupTask: Props=Backup(appParts=[APP, DATA, EXTDATA], locations=[CLOUD], isSyncOnly=false, syncOption=null, backupCache=false, compressionLevel=FASTEST, isArchiveEnabled=false, backupLimits=null, isForceRedo=false)
17/12/22 08:42:36.069/AppDataChangeChecker: No change in APKs size or version code
17/12/22 08:42:36.070/AppBackupTask: APKs already backed up
17/12/22 08:42:36.260/AppDataChangeChecker: DATA: Backup: 125.06 MB, Current: 125.13 MB, Diff: 76 KB
17/12/22 08:42:36.320/AppDataChangeChecker: EXTDATA: Backup: 10.43 MB, Current: 10.65 MB, Diff: 224 KB
17/12/22 08:42:36.321/AppBackupTask: Tasks to perform = Data, ExtData
17/12/22 08:42:36.344/AppBackupTask: Backing up Data (125.13 MB, Cache=false, format=5)
17/12/22 08:42:36.346/AppBackupTask: Copying Data files
17/12/22 08:42:36.833/AppBackupTask: Copying DE Data files (Cache=false)
17/12/22 08:42:36.841/AppBackupTask: Compressing Data files
17/12/22 08:42:37.181/MultiCompressor: Compression results:  Completed in 0.33 s. 123.25 MB => 64.91 MB (-58.34 MB)
17/12/22 08:42:37.587/MultiCompressor: Compression results:  Completed in 0.01 s. 3 KB => 268 B (-2.74 KB)
17/12/22 08:42:37.590/AppBackupTask: Packing Data files
17/12/22 08:42:37.591/SevenZipPacker: Encryption strategy: Standard
17/12/22 08:42:38.770/AppBackupTask: Backing up Ext data (10.65 MB, Cache=false, format=5)
17/12/22 08:42:38.773/AppBackupTask: Copying Ext Data files
17/12/22 08:42:38.854/AppBackupTask: Compressing Ext Data files
17/12/22 08:42:38.891/MultiCompressor: Compression results:  Completed in 0.03 s. 10.57 MB => 3.24 MB (-7.33 MB)
17/12/22 08:42:38.924/AppBackupTask: Packing Ext Data files
17/12/22 08:42:38.927/SevenZipPacker: Encryption strategy: Standard
17/12/22 08:42:39.028/AppBackupTask: Backing up permissions
17/12/22 08:42:39.030/AppPermissionsHelper: Permission: WRITE_EXTERNAL_STORAGE
17/12/22 08:42:39.031/AppPermissionsHelper: Permission: READ_EXTERNAL_STORAGE
17/12/22 08:42:39.031/AppPermissionsHelper: Permission: CAMERA
17/12/22 08:42:39.031/AppPermissionsHelper: Permission: POST_NOTIFICATIONS
17/12/22 08:42:39.033/AppPermissionsHelper: Permission: READ_MEDIA_AUDIO
17/12/22 08:42:39.034/AppPermissionsHelper: Permission: READ_MEDIA_VIDEO
17/12/22 08:42:39.034/AppPermissionsHelper: Permission: READ_MEDIA_IMAGES
17/12/22 08:42:39.513/AppBackupTask: Backed up app ssaid = 19aee2b9902f7771
17/12/22 08:42:39.514/AppBackupTask: Saving backup metadata
17/12/22 08:42:39.577/AppUploadTask: Processing upload for app: 阿里云盘 (com.alicloud.databox). Cloud: WebDAV, Tag: Mi 10 Pro.
17/12/22 08:42:39.578/AppUploadTask: Checking cloud for current sync status
17/12/22 08:42:39.587/AppUploadTask: Checking upload for Data
17/12/22 08:42:39.588/AppDataChangeChecker: DATA: Backup: 125.06 MB, Current: 125.13 MB, Diff: 76 KB
17/12/22 08:42:39.588/AppUploadTask: Checking upload for Ext Data
17/12/22 08:42:39.589/AppDataChangeChecker: EXTDATA: Backup: 10.43 MB, Current: 10.65 MB, Diff: 224 KB
17/12/22 08:42:39.589/AppUploadTask: Upload tasks: Data, ExtData
17/12/22 08:42:39.590/AppUploadTask: Uploading Data (64.91 MB)
17/12/22 08:42:51.283/SardineService: <put: SardineException: Error contacting http://192.168.5.1:8989/%E5%A4%87%E4%BB%BD/%E6%89%8B%E6%9C%BA/SwiftBackup_2e687cef5019709d/Mi%2010%20Pro/com.alicloud.databox.dat%20%28Mi%2010%20Pro%29.tmp (500 Internal Server Error)>
17/12/22 08:42:51.397/SardineService: <put: SardineException: Error contacting http://192.168.5.1:8989/%E5%A4%87%E4%BB%BD/%E6%89%8B%E6%9C%BA/SwiftBackup_2e687cef5019709d/Mi%2010%20Pro/com.alicloud.databox.dat%20%28Mi%2010%20Pro%29.tmp (500 Internal Server Error)>
17/12/22 08:42:51.398/CsUploadSession: <executeUpload:: SardineException: Error contacting http://192.168.5.1:8989/%E5%A4%87%E4%BB%BD/%E6%89%8B%E6%9C%BA/SwiftBackup_2e687cef5019709d/Mi%2010%20Pro/com.alicloud.databox.dat%20%28Mi%2010%20Pro%29.tmp (500 Internal Server Error)>
17/12/22 08:42:51.398/CsUploadSession: <addUploadError: SardineException: Error contacting http://192.168.5.1:8989/%E5%A4%87%E4%BB%BD/%E6%89%8B%E6%9C%BA/SwiftBackup_2e687cef5019709d/Mi%2010%20Pro/com.alicloud.databox.dat%20%28Mi%2010%20Pro%29.tmp (500 Internal Server Error)>
17/12/22 08:42:51.400/AppUploadTask: Completed in 11.81 s
17/12/22 08:42:51.400/AppUploadTask: Uploading metadata
17/12/22 08:42:51.401/AppUploadTask: Metadata node=main
17/12/22 08:42:51.705/AppUploadTask: Uploading metadata complete
17/12/22 08:42:52.156/TaskService: Complete
17/12/22 08:42:52.159/TaskNotificationHelper: <1 个应用已跳过云同步
 • 阿里云盘: Error contacting http://192.168.5.1:8989/%E5%A4%87%E4%BB%BD/%E6%89%8B%E6%9C%BA/SwiftBackup_2e687cef5019709d/Mi%2010%20Pro/com.alicloud.databox.dat%20%28Mi%2010%20Pro%29.tmp (500 Internal Server Error)>
17/12/22 08:42:52.163/TaskService: Completed in 16.6 s
[SwiftLogger end]

阿里云webdav日志
2022-12-16T23:33:46.744576Z  INFO aliyundrive_webdav::drive: refresh token succeed refresh_token=821f975e6aad47888359a218c9ef90ee nick_name=kissuny
2022-12-17T00:42:41.270052Z  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 276.684656ms before the next attempt
2022-12-17T00:42:52.064714Z ERROR aliyundrive_webdav::vfs: rename file failed from=/备份/手机/SwiftBackup_2e687cef5019709d/Mi 10 Pro/com.alicloud.databox.dat (Mi 10 Pro).tmp to=/备份/手机/SwiftBackup_2e687cef5019709d/Mi 10 Pro/com.alicloud.databox.dat (Mi 10 Pro) error=HTTP status client error (409 Conflict) for url (https://api.aliyundrive.com/v2/file/update)

**Comment by messense** [comment]
看起来是这个 App 试图重命名文件名为一个已经存在的文件导致的冲突。
