### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by fyfh** [messense/aliyundrive-webdav#69]
Oct 10 02:20:47.581 ERROR aliyundrive_webdav::drive: refresh token failed: error sending request for url (https://websv.aliyundrive.com/token/refresh): error trying to connect: tcp connect error: Connection refused (os error 111)

Error: initialize aliyundrive file system failed

**Comment by messense** [comment]
看起来是网络问题。

**Comment by fyfh** [comment]
已解决

**Comment by messense** [comment]
> 已解决

什么问题导致的，怎么解决的呢？

**Comment by fyfh** [comment]
https://github.com/coolsnowwolf/lede/issues/1760#issuecomment-542985373
按上面方法解决了
