### ISSUE TITLE
aliyundrive-webdav 1.10.6 未运行

### ISSUE THREAD

**Issue by Qitain** [messense/aliyundrive-webdav#690]
### 问题描述

openWrt下出现这种情况，无法正常运行，有没有解决方案？

### 重现步骤

`wget https://github.com/messense/aliyundrive-webdav/releases/download/v1.10.6/aliyundrive-webdav_1.10.6-1_x86_64.ipk
wget https://github.com/messense/aliyundrive-webdav/releases/download/v1.10.6/luci-app-aliyundrive-webdav_1.10.6_all.ipk
wget https://github.com/messense/aliyundrive-webdav/releases/download/v1.10.6/luci-i18n-aliyundrive-webdav-zh-cn_1.10.6-1_all.ipk
opkg install aliyundrive-webdav_1.10.6-1_x86_64.ipk
opkg install luci-app-aliyundrive-webdav_1.10.6_all.ipk
opkg install luci-i18n-aliyundrive-webdav-zh-cn_1.10.6-1_all.ipk`

### 版本

1.10.6

### 运行平台

openWrt

### refresh token 获取方式

网页版

### 日志

023-01-25T14:23:33.998593Z  INFO aliyundrive_webdav::drive: found default drive drive_id=2016600
thread 'main' panicked at 'error binding to 0.0.0.0:8080: error creating server listener: Address in use (os error 98)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/server/server.rs:79:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by messense** [comment]
Address in use
