### ISSUE TITLE
在网速不足的时候302重定向的链接会在一定时间后失效

### ISSUE THREAD

**Issue by miaopasimiao** [messense/aliyundrive-webdav#691]
### 问题描述

下载一个比较大的文件 在网速不足时 大约20分钟左右链接就会失效 有办法延长链接时间么

### 重现步骤

下载超过时间链接会失效

### 版本

1.10.6

### 运行平台

linux openwrt

### refresh token 获取方式

.

### 日志

<Code>AccessDenied</Code>
<Message>Request has expired.</Message>
<HostId>cn-beijing-data.aliyundrive.net</HostId>

**Comment by messense** [comment]
那就关闭重定向功能。
