### ISSUE TITLE
复制图片出错

### ISSUE THREAD

**Issue by zephyr-y** [messense/aliyundrive-webdav#721]
### 问题描述

rclone无法拷贝云盘里的图片(png,jpg,webp)，提示 Removing partially written file on error: unexpected EOF
浏览器里也无法访问这个图片
我刚使用，是版本问题么？
@messense 

### 重现步骤

1、无法copy图片
2、浏览器中无法访问图片

### 版本

最新main或者latest

### 运行平台

debian11，docker运行

### refresh token 获取方式

网页版

### 日志

Removing partially written file on error: unexpected EOF

**Comment by messense** [comment]
暂无修复计划。
