### ISSUE TITLE
启动前自动更新无法工作

### ISSUE THREAD

**Issue by A1LExX** [messense/aliyundrive-webdav#779]
### 问题描述

这个是我的网络问题导致的401权限问题还是由于国内网络的原因？
我的网络是具备外网访问能力的

### 重现步骤

每次启动时会报这个警告，我只能进行手动更新

### 版本

v2.0.3

### 运行平台

openwrt N1

### 日志

WARN aliyundrive_webdav: failed to check for update: NetworkError: api request failed with status: 401 - for: "https://api.github.com/repos/messense/aliyundrive-webdav/releases/latest"

**Comment by A1LExX** [comment]
了解，我有解决方案了

**Comment by a350844866** [comment]
咋解决的
