### ISSUE TITLE
operation timed out

### ISSUE THREAD

**Issue by 78182428** [messense/aliyundrive-webdav#797]
### 问题描述

2023-04-02T05:10:20.533944Z  INFO aliyundrive_webdav: Please scan the qrcode to login in 30 seconds
Error: error sending request for url (https://openapi.aliyundrive.com/oauth/qrcode/ef917fbe13db463591d73f4f2b157626/status): error trying to connect: operation timed out

Caused by:
    0: error trying to connect: operation timed out
    1: operation timed out

### 重现步骤

sudo snap install aliyundrive-webdav
运行 aliyundrive-webdav
出现二维码后 扫码无反应 出现超时

### 版本

最新版

### 运行平台

ubuntu 

### 日志

2023-04-02T05:10:20.533944Z  INFO aliyundrive_webdav: Please scan the qrcode to login in 30 seconds
Error: error sending request for url (https://openapi.aliyundrive.com/oauth/qrcode/ef917fbe13db463591d73f4f2b157626/status): error trying to connect: operation timed out

Caused by:
    0: error trying to connect: operation timed out
    1: operation timed out

**Comment by messense** [comment]
网络问题自行排查。
