### ISSUE TITLE
webdav 64 exe的二维码一直是错乱的

### ISSUE THREAD

**Issue by jdAction** [messense/aliyundrive-webdav#800]
### 问题描述

这是默认打开的时候展示的二维码
![image](https://user-images.githubusercontent.com/87454525/230250859-27b11d98-372c-4f5f-8ea2-b8bf0b6bdb07.png)
我想调整窗口让它达到一个正方形也不行
![image](https://user-images.githubusercontent.com/87454525/230250942-2e860159-9d9e-4b9d-8ef2-f138016cff32.png)

### 重现步骤

1.下载x64 exe
2.直接打开改软件

### 版本

2.1.0

### 运行平台

Windows

### 日志

Error: Invalid refresh token value found in `--refresh-token` argument
Error: Invalid refresh token value found in `--refresh-token` argument
Error: Invalid refresh token value found in `--refresh-token` argument
Error: Invalid refresh token value found in `--refresh-token` argument
Error: Invalid refresh token value found in `--refresh-token` argument
Error: Invalid refresh token value found in `--refresh-token` argument
Error: Invalid refresh token value found in `--refresh-token` argument
Error: Invalid refresh token value found in `--refresh-token` argument

**Comment by messense** [comment]
用 Windows Terminal.

提问请先搜索。
