### ISSUE TITLE
windows网络映射挂载webdav无法打开视频文件，但是doc之类文件可以打开

### ISSUE THREAD

**Issue by YOU-Y8** [messense/aliyundrive-webdav#840]
### 问题描述

在阿里云盘更新api前的1.x版本都可以正常挂载，跟本地硬盘一样播放视频文件。
后来就一直无法打开视频文件。但是用potplayer挂载webdav地址却可以播放视频

### 重现步骤

此电脑-右键映射网络驱动器-输入webdav地址和端口-在文件夹双击打开视频文件

### 版本

2.2.1

### 运行平台

n1， openwrt 5.15.93

### 日志

日志无报错信息

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-webdav/issues/117#issuecomment-982687485
