### ISSUE TITLE
获取refresh token失败

### ISSUE THREAD

**Issue by loloku798** [messense/aliyundrive-webdav#844]
### 问题描述

获取refresh token失败

### 重现步骤

按照步骤一步步的安装并设置，在通过连接获取refresh token时，页面无法加载。
通过机场仍无法打开页面。
是否还有其它方式可以获取refresh token？或是否可以把获取refresh token的服务更换一个地址？

### 版本

latest

### 运行平台

Synology NAS docker

### 日志

Error: get access_token failed
 refresh token failed: Request error: error sending request for url (https://aliyundrive-oauth.messense.me/oauth/access_token): error trying to connect: dns error: failed to lookup address information: Try again

**Comment by JashLee0211** [comment]
r2s 的包也有一样的问题

**Comment by loloku798** [comment]
> r2s 的包也有一样的问题

所以，目前真的没有什么好的解决办法吗，不知道是程序的问题还是网站的问题，总之，就是refresh token失败。

**Comment by messense** [comment]
> 是否还有其它方式可以获取refresh token？

自行申请个阿里云云盘发者账号，部署 https://github.com/messense/aliyundrive-webdav/blob/main/backend/app.py 并设置环境变量 `ALIYUNDRIVE_OAUTH_SERVER` 为你的服务地址比如 https://example.com


> 或是否可以把获取refresh token的服务更换一个地址？

Nope，没有国内备案的域名，换个地址也是迟早被 GFW and/or 你的电信服务商限制访问。

**Comment by Observer5** [comment]
在网关里通过docker安装，也是这个问题

**Comment by d-maxheman** [comment]
> ### 问题描述
> 获取refresh token失败
> 
> ### 重现步骤
> 按照步骤一步步的安装并设置，在通过连接获取refresh token时，页面无法加载。 通过机场仍无法打开页面。 是否还有其它方式可以获取refresh token？或是否可以把获取refresh token的服务更换一个地址？
> 
> ### 版本
> latest
> 
> ### 运行平台
> Synology NAS docker
> 
> ### 日志
> Error: get access_token failed refresh token failed: Request error: error sending request for url (https://aliyundrive-oauth.messense.me/oauth/access_token): error trying to connect: dns error: failed to lookup address information: Try again

断开科学网络，就可以在token栏双击扫码刷新，就正常了。

**Comment by d-maxheman** [comment]
> > r2s 的包也有一样的问题
> 
> 所以，目前真的没有什么好的解决办法吗，不知道是程序的问题还是网站的问题，总之，就是refresh token失败。

断开科学网络，就可以在token栏双击扫码刷新，就正常了。

**Comment by d-maxheman** [comment]
> > 是否还有其它方式可以获取refresh token？
> 
> 自行申请个阿里云云盘发者账号，部署 https://github.com/messense/aliyundrive-webdav/blob/main/backend/app.py 并设置环境变量 `ALIYUNDRIVE_OAUTH_SERVER` 为你的服务地址比如 https://example.com
> 
> > 或是否可以把获取refresh token的服务更换一个地址？
> 
> Nope，没有国内备案的域名，换个地址也是迟早被 GFW and/or 你的电信服务商限制访问。

没错，科学网络下会被ban导致无法获取token。

**Comment by amibaren** [comment]
> > 是否还有其它方式可以获取refresh token？
> 
> 自行申请个阿里云云盘发者账号，部署 https://github.com/messense/aliyundrive-webdav/blob/main/backend/app.py 并设置环境变量 `ALIYUNDRIVE_OAUTH_SERVER` 为你的服务地址比如 https://example.com
> 
> > 或是否可以把获取refresh token的服务更换一个地址？
> 
> Nope，没有国内备案的域名，换个地址也是迟早被 GFW and/or 你的电信服务商限制访问。

有两个问题？
1、能否把这个app.py部署在家里内网的NAS上面？
2、环境变量 `ALIYUNDRIVE_OAUTH_SERVER`能否不使用域名直接使用IP？
