### ISSUE TITLE
群晖 Cloud Sync  系统错误

### ISSUE THREAD

**Issue by qianxunclub** [messense/aliyundrive-webdav#850]
### 问题描述

aliyundrive-webdav 使用 docker 部署，使用群晖的 Cloud Sync 同步出现提示“系统错误”，aliyundrive-webdav  错误日志：

```
[2m<unknown time>[0m [31mERROR[0m [2maliyundrive_webdav::vfs[0m[2m:[0m get_by_path failed [3mpath[0m[2m=[0m/@SynologyCloudSync [3merror[0m[2m=[0mHTTP status client error (400 Bad Request) for url (https://openapi.aliyundrive.com/adrive/v1.0/openFile/get_by_path) 
```

### 重现步骤

1. docker 部署 aliyundrive-webdav
2. 访问 8080 是可以展示阿里云盘目录结构的
3. 使用群晖 Cloud Sync 设置同步
<img width="661" alt="图片" src="https://github.com/messense/aliyundrive-webdav/assets/11555911/d5f64047-0581-4b0f-8fac-f67ca7eb9dcd">

### 版本

 messense/aliyundrive-webdav:sha-5c2fb0a

### 运行平台

docker

### 日志

[2m<unknown time>[0m [31mERROR[0m [2maliyundrive_webdav::vfs[0m[2m:[0m get_by_path failed [3mpath[0m[2m=[0m/@SynologyCloudSync [3merror[0m[2m=[0mHTTP status client error (400 Bad Request) for url (https://openapi.aliyundrive.com/adrive/v1.0/openFile/get_by_path)

**Comment by messense** [comment]
Duplicate of #813
