### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by haitun001** [messense/aliyundrive-webdav#86]
您好，用openwrt版本的挂在到webdav后，用rclone挂在到linux服务器做本地目录后发现用rsync大量同步文件时，openwrt这边的webdav服务会挂掉。

**Comment by messense** [comment]
看起来这个应该和 https://github.com/messense/aliyundrive-webdav/issues/58 是一样的问题，在 0.4.2 版本就已经修复了，更新成最新版本试下吧。
