### ISSUE TITLE
rclone 挂载 cp 文件 OOM

### ISSUE THREAD

**Issue by haitun001** [messense/aliyundrive-webdav#87]
![luci设置](https://user-images.githubusercontent.com/22430419/138020983-666ade73-3394-4edd-89a7-e528d66c4aea.png)
这个是luci的设置截图，用rclone挂在用的cp命令。
这个是rclone的挂载命令:/usr/bin/rclone mount alidrive:/ /home/alidrive --vfs-cache-mode writes --vfs-cache-max-age 10s --allow-other --buffer-size 200M --cache-dir /tmp --allow-non-empty
下面贴一下日志。
版本是0.4.7目前luci界面已经打勾但是未运行状态了。
[2mOct 20 01:45:49.680[0m [32m INFO[0m aliyundrive_webdav::drive: refresh token succeed refresh_token=xxx nick_name=娴疯睔438
[2mOct 20 01:45:49.680[0m [32m INFO[0m aliyundrive_webdav::drive: found default drive drive_id=4377724
[2mOct 20 01:45:49.680[0m [32m INFO[0m aliyundrive_webdav: listening on 0.0.0.0:8088
[2mOct 20 01:51:13.302[0m [32m INFO[0m aliyundrive_webdav::drive: refresh token succeed refresh_token=xxx nick_name=娴疯睔438
[2mOct 20 01:51:13.302[0m [32m INFO[0m aliyundrive_webdav::drive: found default drive drive_id=4377724
[2mOct 20 01:51:13.302[0m [32m INFO[0m aliyundrive_webdav: listening on 0.0.0.0:8088

**Comment by messense** [comment]
可以运行 `dmesg` 或者 luci 界面上看看系统、内核日志找找有没有 oom 的日志记录。

**Comment by haitun001** [comment]
另外，我下载了x86-64的二进制文件，在我的debian系统上提示无法执行这个二进制文件，我用pip install安装的也是如此提示。

**Comment by haitun001** [comment]
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3292.374
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat umip arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest shadow_vmcs pml
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs srbds
bogomips	: 6584.74
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**Comment by haitun001** [comment]
我看了一下，我好像是没法解决openwrt杀死进程，所以想在debian上跑。结果就这样，不行看看研究一下docker吧。但是按理说不应该在x64下不能跑。

**Comment by haitun001** [comment]
不是的，我chmod +x 是基本操作，我一开始是认为我认错了指令集，但是后来反复尝试的确就是不能执行。随后我在看看吧。pip的也不行 加了/bin/bash在跟上文件也不行。

**Comment by messense** [comment]
`file aliyundrive-webdav` 看下输出。

**Comment by haitun001** [comment]
好的，感谢耐心解答。

**Comment by messense** [comment]
OOM 暂时也做不了太多改进。
