### ISSUE TITLE
无法获取 refresh token

### ISSUE THREAD

**Issue by lewis2060** [messense/aliyundrive-webdav#896]
### 问题描述

获取 refresh token
[通过在线工具获取 refresh token](https://messense-aliyundrive-webdav-backendrefresh-token-ucs0wn.streamlit.app/)
命令行运行 aliyundrive-webdav qr login 

现在均无法获取 refresh token

### 重现步骤

扫码之后，阿里云盘app跳转不正常，跳转到了阿里云盘下载页

### 版本

2.3.2

### 运行平台

群晖

### 日志

扫码之后，阿里云盘app跳转不正常，跳转到了阿里云盘下载页

**Comment by chuds001** [comment]
我是openwrt 也出现这种情况，如何解决？

**Comment by oupengopu** [comment]
我也是这种情况

**Comment by yangliuchang** [comment]
我是openwrt也遇到了

**Comment by wogong** [comment]
同遇到了，[通过在线工具获取 refresh token](https://messense-aliyundrive-webdav-backendrefresh-token-ucs0wn.streamlit.app/) 这个链接也是同样的问题。

**Comment by springeye** [comment]
我也遇到了，扫码直接跳转到阿里云盘下载页面

**Comment by Husky-lee** [comment]
降级到阿里云盘4.9.1版本呗

**Comment by springeye** [comment]
用阿里云小程序可以扫码

**Comment by jianghaodn** [comment]
可以先登录阿里云盘小程序，再用微信直接扫码就行了。不要用阿里云盘app
