### ISSUE TITLE
Openwrt 23.05下不显示界面

### ISSUE THREAD

**Issue by mrlong32** [messense/aliyundrive-webdav#897]
### 问题描述

Openwrt 23.05下不显示界面

### 重现步骤

安装完luci-app-aliyundrive-webdav_2.3.2_all.ipk没有菜单项

### 版本

2.3.2-1

### 运行平台

Openwrt

### 日志

没有日志

**Comment by jinlin-teck** [comment]
重启openwrt才行。。。。
