### ISSUE TITLE
aliyundrive-oauth.messense.me 网络被劣化

### ISSUE THREAD

**Issue by biaji** [messense/aliyundrive-webdav#902]
### 问题描述

docker提示：

<unknown time> ERROR aliyundrive_webdav::drive: refresh token failed: Request error: error sending request for url (https://aliyundrive-oauth.messense.me/oauth/access_token): error trying to connect: operation timed out

ping发现普通网络环境大量丢包：

```shell
ping aliyundrive-oauth.messense.me
PING aliyundrive-oauth.fly.dev (66.241.124.60) 56(84) 字节的数据。
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=27 ttl=51 时间=267 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=29 ttl=51 时间=271 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=52 ttl=51 时间=271 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=83 ttl=51 时间=280 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=88 ttl=51 时间=290 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=118 ttl=51 时间=305 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=142 ttl=51 时间=297 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=204 ttl=51 时间=295 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=234 ttl=51 时间=280 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=396 ttl=51 时间=307 毫秒
64 字节，来自 66.241.124.60 (66.241.124.60): icmp_seq=507 ttl=51 时间=301 毫秒
```

更换国外网络环境发现一切正常。

### 重现步骤

1. docker 报错
2. 普通网路环境ping测试（电信）
3. 外网vps测试

### 版本

2.3.2

### 运行平台

Docker

### 日志

<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 123.418097ms before the next attempt
--

<pre class="allowDefCtxMenu selectabletext" ext:qtip="Error: get access_token failed
">Error: get access_token failed</pre>[5 个项目。](http://192.168.1.202:27746/#)

<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 123.418097ms before the next attempt

<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 146.21117ms before the next attempt

<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 892.161251ms before the next attempt

<unknown time> ERROR aliyundrive_webdav::drive: refresh token failed: Request error: error sending request for url (https://aliyundrive-oauth.messense.me/oauth/access_token): error trying to connect: operation timed out

Error: get access_token failed

**Comment by biaji** [comment]
refresh token可能需要加入代理支持

**Comment by jsuny1008** [comment]
和你问题一样，不知道什么原因。

**Comment by biaji** [comment]
> 和你问题一样，不知道什么原因。

可以在docker环境变量里定义https_proxy指定代理服务器绕过这个问题。但代理服务需要对aliyun的数据传输做直传例外。

**Comment by messense** [comment]
![IMG_2629](https://github.com/messense/aliyundrive-webdav/assets/1556054/0c329cdb-bee2-4d66-b40d-3292f2ed8f1d)
