### ISSUE TITLE
aliyundrive-webdav 2.3.2 resource driver issue

### ISSUE THREAD

**Issue by Jas0n0ss** [messense/aliyundrive-webdav#904]
### 问题描述

> system info
```bash
[root@WRT:01:39 PM ~] # uname -a
Linux WRT 5.15.127 #0 SMP Tue Aug 22 05:54:08 2023 x86_64 GNU/Linux
[root@WRT:01:39 PM ~] # cpuinfo
Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz x 4C 4T (1366.538MHz, 58.0°C)
```
> when I change driver to `resource` , will receive `404`

```bash
# logs
<unknown time>  INFO aliyundrive_webdav::drive: found resource drive drive_id=xxxxxxxxx
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8090

# test connection
root@srv:~# curl -I http://192.168.4.1:8090 --user admin:xxxxx
HTTP/1.1 404 Not Found
content-length: 0
date: Thu, 21 Sep 2023 05:23:54 GMT
```
> when I change driver back  to `backup` , it's all good and received `200`
```bash
# log
<unknown time>  INFO aliyundrive_webdav::drive: found backup drive drive_id=xxxxxxx
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8090
# test connection
root@srv:~# curl -I http://192.168.4.1:8090 --user admin:xxxxxxx
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
date: Thu, 21 Sep 2023 05:36:35 GMT
```
We would like to know if this is a bug or something, anyone, any ideas?

### 重现步骤
> when I change driver to `resource` , will receive `404`

```bash
# logs
<unknown time>  INFO aliyundrive_webdav::drive: found resource drive drive_id=xxxxxxxxx
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8090

# test connection
root@srv:~# curl -I http://192.168.4.1:8090 --user admin:xxxxx
HTTP/1.1 404 Not Found
content-length: 0
date: Thu, 21 Sep 2023 05:23:54 GMT
```
> when I change driver back  to `backup` , it's all good and received `200`
```bash
# log
<unknown time>  INFO aliyundrive_webdav::drive: found backup drive drive_id=xxxxxxx
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8090
# test connection
root@srv:~# curl -I http://192.168.4.1:8090 --user admin:xxxxxxx
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
date: Thu, 21 Sep 2023 05:36:35 GMT
```
### 版本

aliyundrive-webdav 2.3.2

### 运行平台

Intel(R) Celeron(R) CPU  J1900 X86

### 日志

```bash
# logs
<unknown time>  INFO aliyundrive_webdav::drive: found resource drive drive_id=xxxxxxxxx
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8090

# test connection
root@srv:~# curl -I http://192.168.4.1:8090 --user admin:xxxxx
HTTP/1.1 404 Not Found
content-length: 0
date: Thu, 21 Sep 2023 05:23:54 GMT
```

**Comment by gngpp** [comment]
没啥问题吧
![Uploading image.png…]()

**Comment by gngpp** [comment]
日志你没补全，实际上服务起不来
![image](https://github.com/messense/aliyundrive-webdav/assets/51810656/850c9242-4c80-4dcd-a03c-f763e1ba7bd9)

**Comment by Jas0n0ss** [comment]
> 我账号只有default的服务，没法测试 ![image](https://user-images.githubusercontent.com/51810656/270136901-69e168e9-c945-4f40-8ebc-d42fbcc83d99.png)

感谢及时回复
---
我发现问题的主要原因出在哪了，默认所有的资源都存在`备份盘`，`资源库`里面是空的,所以`backup driver` **200**, `resource driver` **404**
![image](https://github.com/messense/aliyundrive-webdav/assets/88020021/3acc8d76-368f-42eb-aec4-a229fa38317f)
![image](https://github.com/messense/aliyundrive-webdav/assets/88020021/c99cffc8-ac44-4380-82c2-13e12f528913)

**Comment by Jas0n0ss** [comment]
> 我账号只有default的服务，没法测试
> 
> ![image](https://github.com/messense/aliyundrive-webdav/assets/51810656/69e168e9-c945-4f40-8ebc-d42fbcc83d99)
> 
> 

感谢回复，我发现问题原因了，在阿里云盘内部，我只有
