### ISSUE TITLE
windows版本二维码错位

### ISSUE THREAD

**Issue by zhongyuanqi** [messense/aliyundrive-webdav#913]
### 问题描述

我用的【aliyundrive-webdav-v2.3.3.x86_64-pc-windows-msvc】

### 重现步骤

1.双击解压后的exe
2.扫二维码界面，但是二维码是错位的，无法扫，请看截图
[https://tu.wnflb2023.com/i/2023/10/09/180005.png](url)

### 版本

2.3.3

### 运行平台

Windows

### 日志

二维码错位

**Comment by zhongyuanqi** [comment]
我是用Windows自带的【远程桌面连接】工具下远程操作出现的

**Comment by messense** [comment]
用 Windows Terminal 不要用辣鸡 cmd.
