### ISSUE TITLE
链接不上了, 提示进程运行正常后 过几秒之后就断了

### ISSUE THREAD

**Issue by a497500306** [messense/aliyundrive-webdav#916]
### 问题描述

华硕AX86U  
aliyundrive-webdav 2.1.0

### 重现步骤

r

### 版本

2.1.0

### 运行平台

华硕AX86U

### 日志

未找到日志查看的入口

**Comment by 8038707** [comment]
今天我也是出现同样的问题,启动正常几秒后就显示 进程未在运行

**Comment by amibaren** [comment]
容器日志提示get access token failed，尝试多次从https://messense-aliyundrive-webdav-backendrefresh-token-ucs0wn.streamlit.app 更新token刷新容器配置后重启容器依然无法使用，容器会自动停止。已拉去最新的镜像。

**Comment by StormFeng** [comment]
同样报错 `get access_token failed`，应该是阿里云盘动了哪里，坐等解决方案

**Comment by Sunshine214000** [comment]
我也是

**Comment by messense** [comment]
科学上网。
