### ISSUE TITLE
群晖docker版本经常报错，无法连接

### ISSUE THREAD

**Issue by 404gods** [messense/aliyundrive-webdav#917]
### 问题描述

群晖docker，更新了最新的2.3.3版本，很难连接上，大部分时间都是报错，偶尔可以连接成功，报错日志图片如下，请问是什么问题？

### 重现步骤

不通过镜像网站，直接拉取官方镜像，使用阿里云盘APP扫描官方提供的获取 refresh token网址(https://messense-aliyundrive-webdav-backendrefresh-token-ucs0wn.streamlit.app/)成功获取 refresh token，填入docker变量

### 版本

2.3.3

### 运行平台

官方docker镜像

### 日志

![Snipaste_2023-10-22_15-47-25](https://github.com/messense/aliyundrive-webdav/assets/50573302/e945c4bc-a973-432d-a671-acf43ae6c05b)

**Comment by 404gods** [comment]
刚才试了强制messense.me走代理规则，好像可以用了

**Comment by nrjycyd** [comment]
> 刚才试了强制messense.me走代理规则，好像可以用了

好方法，解决了
