### ISSUE TITLE
OpenWrt plugin has a command injection vulnerability

### ISSUE THREAD

**Issue by lakemoon602** [messense/aliyundrive-webdav#972]
### 问题描述

vuln file: https://github.com/messense/aliyundrive-webdav/openwrt/luci-app-aliyundrive-webdav/luasrc/controller/aliyundrive-webdav.lua

### 重现步骤

When deal with `action_query_qrcode` request,`sid` parameter is vulnerable to OS command injection.
![1](https://github.com/messense/aliyundrive-webdav/assets/55305755/63f8ef41-05a5-4172-9045-1fc2dac0a871)
![2](https://github.com/messense/aliyundrive-webdav/assets/55305755/c2339d64-ef4a-4778-ae5b-3fd3e600d5ff)
![3](https://github.com/messense/aliyundrive-webdav/assets/55305755/e9c549f2-4a10-4066-a6d9-37241aeb60a2)

### 版本

2.3.3

### 运行平台

Openwrt

### 日志

![1](https://github.com/messense/aliyundrive-webdav/assets/55305755/7c3aa775-a7f3-4989-b3b0-25d7fbf4fb08)

**Comment by messense** [comment]
都登录进路由器后台了，早有 root 权限了，纠结这点问题意义不大吧。
