### ISSUE TITLE
阿里云webdav插件无法进入根目录展示全部云盘内容或者展示资源盘（资源库和备份盘UI已合并）

### ISSUE THREAD

**Issue by hztbhtbh** [messense/aliyundrive-webdav#988]
### 问题描述

最近资源库和备份盘UI已合并以后出现不能访问资源库文件了，
![1](https://github.com/messense/aliyundrive-webdav/assets/104251804/7284eb15-9d63-45ab-85c6-6fbad0812b91)
![2](https://github.com/messense/aliyundrive-webdav/assets/104251804/bbaf4edb-7dda-4509-b06e-debb16647176)

### 重现步骤

1.最近资源库和备份盘已合并以后出现不能访问
2.云盘根目录还是默认的：/

### 版本

V2.3.2

### 运行平台

X86软路由openwrt系统Lede源码编译安装阿里云webdav插件

### 日志

<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 252.270075ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 146.97528ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 191.012291ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 515.755257ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 252.46876ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 78.099137ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 628.298109ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 107.621014ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 336.409368ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 281.529452ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 32.429445ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 376.08282ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 994.018431ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 99.29912ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 285.421086ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 568.457186ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 266.087244ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 254.334604ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 290.885488ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 216.06506ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 12.318105ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 26.763316ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 551.709438ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 179.94996ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 91.649015ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 841.047933ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 109.714076ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 453.041697ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 28.060654ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 92.732553ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 303.839694ms before the next attempt
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 205.324771ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 406.70695ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 191.060476ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 457.200882ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 229.951972ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 952.627µs before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 166.206833ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 70.012439ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 94.332126ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 77.965819ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 165.336917ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 19.959007ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 364.5165ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 35.642296ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 206.316078ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 70.831287ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 210.636543ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 235.086516ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 542.654457ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 197.969739ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 584.245378ms before the next attempt
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 131.448803ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 19.008196ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 69.51822ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 1.030420524s before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 296.615367ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 190.403066ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 56.586461ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 1.17899257s before the next attempt
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=292433770
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8080
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=292433770
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8080
<unknown time> ERROR aliyundrive_webdav::vfs: list_files_and_cache failed path=/电影 error=HTTP status client error (400 Bad Request) for url (https://openapi.aliyundrive.com/adrive/v1.0/openFile/list)
<unknown time> ERROR aliyundrive_webdav::vfs: list_files_and_cache failed path=/音乐视频 error=HTTP status client error (400 Bad Request) for url (https://openapi.aliyundrive.com/adrive/v1.0/openFile/list)
<unknown time> ERROR aliyundrive_webdav::vfs: list_files_and_cache failed path=/4K测试 error=HTTP status client error (400 Bad Request) for url (https://openapi.aliyundrive.com/adrive/v1.0/openFile/list)
<unknown time> ERROR aliyundrive_webdav::vfs: list_files_and_cache failed path=/学习视频 error=HTTP status client error (400 Bad Request) for url (https://openapi.aliyundrive.com/adrive/v1.0/openFile/list)
<unknown time> ERROR aliyundrive_webdav::vfs: list_files_and_cache failed path=/音乐视频 error=HTTP status client error (400 Bad Request) for url (https://openapi.aliyundrive.com/adrive/v1.0/openFile/list)
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 142.668996ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 314.086325ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 445.445718ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 198.868853ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #0. Sleeping 257.364453ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #1. Sleeping 343.833672ms before the next attempt
<unknown time>  WARN reqwest_retry::middleware: Retry attempt #2. Sleeping 340.586796ms before the next attempt
error: a value is required for '--root <ROOT>' but none was supplied

For more information, try '--help'.
error: a value is required for '--root <ROOT>' but none was supplied

For more information, try '--help'.
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=292433770
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8080
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=292433770
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8080
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=292433770
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8080
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=292433770
<unknown time>  INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8080

**Comment by AlanWang2333** [comment]
还能用么，我的怎么不能用
